### PR TITLE
Fix printing type constants like `double`

### LINKED ISSUE #4268: "type" expressions don't have a printed form
Executing `print double;` in Master prints an empty string. Seems it should provide the name of the type.

### PR DESCRIPTION
**Pull request by evantypanski**
Fixes #4268

### CODE REVIEW

File: src/Val.cc [hunk 1]
```diff
@@ -3202,7 +3202,13 @@ ValPtr EnumVal::DoClone(CloneState* state) {
...
 }
 
-void TypeVal::ValDescribe(ODesc* d) const { d->Add(type->AsTypeType()->GetType()->GetName()); }
+void TypeVal::ValDescribe(ODesc* d) const {
+    const auto& ty = type->AsTypeType()->GetType();
+    if ( ty->GetName().empty() )
+        d->Add(type_name(ty->Tag()));
+    else
+        d->Add(ty->GetName());
+}
```
Comment (awelzel) [inline src/Val.cc:3211]: WDYT about using `type->Describe(ODesc *)` instead?

Comment (evantypanski) [reply src/Val.cc:3211]: Yeah I'll change to that. I figured for something tiny changing less would be preferred and I didn't want to change existing type vals, but turns out with a name a lot will just print the name anyway... so that's a wash :)

**Review by awelzel — APPROVED** [review]
