### PR TITLE
DNS_Mgr: Replace ares_fds() with ares_getsock()

### LINKED ISSUE #3309: DNS_Mgr::GetNextTimeout(): ares_fds: __GI___fortify_fail / "buffer overflow detected"
From [Slack, h-mikami](https://zeekorg.slack.com/archives/CSZBXF6TH/p1695107926917089?thread_ts=1685587437.627989&cid=CSZBXF6TH) - this is a 5.0.10 deployment with "fortify source" enabled from the looks of it.

gdb backtrace is:
worker-1-3
```
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f3158c35859 in __GI_abort () at abort.c:79
#2  0x00007f3158ca026e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f3158dca08f "*** %s ***: terminated\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f3158d42aba in __GI___fortify_fail (msg=msg@entry=0x7f3158dca025 "buffer overflow detected") at fortify_fail.c:26
#4  0x00007f3158d41356 in __GI___chk_fail () at chk_fail.c:28
#5  0x00007f3158d429fb in __fdelt_chk (d=<optimized out>) at fdelt_chk.c:25
#6  0x000055c18f6f90b4 in ares_fds (channel=0x7f3151e27980, read_fds=read_fds@entry=0x7ffd9c7bb890, write_fds=write_fds@entry=0x7ffd9c7bb910)
    at /root/work/zeek_v5010/zeek/auxil/c-ares/src/lib/ares_fds.c:41
#7  0x000055c18ef74920 in zeek::detail::DNS_Mgr::GetNextTimeout (this=0x7f31588d0000) at /root/work/zeek_v5010/zeek/src/DNS_Mgr.cc:1452
#8  0x000055c18f2867cf in zeek::iosource::Manager::FindReadySources (this=0x7f31588520c0, ready=ready@entry=0x7ffd9c7bba30) at /root/work/zeek_v5010/zeek/src/iosource/Manager.cc:144
#9  0x000055c18f065296 in zeek::run_state::detail::run_loop () at /root/work/zeek_v5010/zeek/src/RunState.cc:292
#10 0x000055c18eda7abf in main (argc=<optimized out>, argv=<optimized out>) at /root/work/zeek_v5010/zeek/src/main.cc:59
```

One reasonable good StackOverflow hit indicates that there might be an `fd` involved that's > `FD_SETSIZE`.

https://stackoverflow.com/a/70572070

> You are either crossing FD_SETSIZE limit, or have negative number of fds. Glibc checks this internally and causes crash if check will fail: https://github.com/lattera/glibc/blob/master/debug/fdelt_chk.c
> Daniel Received on 2017-08-01

Here are a few hints how to remove `ares_fds()` - though in the `GetNextTimeout()` code we only ever want to know if there are any FDs - can probably handle differently.
https://github.com/c-ares/c-ares/issues/254

This has also [happened with Zeek 5.0.9](https://app.slack.com/client/TSXGCHZE1/CSZBXF6TH/thread/CSZBXF6TH-1685587437.627989). Not new with 5.0.10. Zeek 6.0 is likely also affected.

### PR DESCRIPTION
**Pull request by awelzel**
On Slack, a user reported "fortify source" aborts within ares_fds() due to the FDs used by c-ares exceeding 1024 and thereby larger than the maximum fd value that a fd_set can hold.

Switch to ares_get_socks() and poll() to avoid this.

Closes #3309.

---

This needs: https://github.com/zeek/libunistd/pull/5

### CODE REVIEW

File: src/DNS_Mgr.cc [hunk 1]
```diff
@@ -992,23 +992,54 @@ void DNS_Mgr::Resolve()
...
 			break;
 
+		// poll() timeout is in milliseconds.
 		tvp = ares_timeout(channel, &tv, &tv);
-		int res = select(nfds, &read_fds, &write_fds, NULL, tvp);
-		if ( res >= 0 )
-			ares_process(channel, &read_fds, &write_fds);
+		int timeout_ms = tvp->tv_sec * 1000 + tvp->tv_usec / 1000;
+
+		int res = poll(pollfds, nfds, timeout_ms);
```
Comment (awelzel) [inline src/DNS_Mgr.cc:1027]: Tim asked why we're using poll() directly instead of going through kqueue. It had been using `select()` directly before, so that's not much different. It's the code path used for synchronous lookups and during shutdown, so it was probably difficult to plumb together with the async IO loop.

**Review by timwoj — APPROVED** [review]
