### PR TITLE
Fixes for Coverity issues

### LINKED ISSUE #527: Fix Coverity issues before 3.0.0 RC
A few Coverity issues look legit that I'll take a look at: memory leaks in new Frame unserialization code and maybe an MQTT bug.

### PR DESCRIPTION
**Pull request by jsiwek**
Fixes #527

### CODE REVIEW

File: src/Frame.cc [hunk 1]
```diff
@@ -467,15 +507,27 @@ Frame::UnserializeIDList(const broker::vector& data)
...
 
 		std::advance(where, 1);
 
 		auto has_offset = broker::get_if<broker::integer>(*where);
 		if ( ! has_offset )
+			{
+			for ( auto& i : rval )
+				Unref(i);
+
+			rval = id_list{};
```
Comment (timwoj) [inline src/Frame.cc]: Doesn't this still leak the `id` new'd above?

Comment (jsiwek) [reply src/Frame.cc]: Yep, fixed it, thanks.
