### PR TITLE
GH-532: improve disable_analyzer BIF

### LINKED ISSUE #532: disable_analyzer doesn't work on TCP_ApplicationAnalyzer's
`disable_analyzer` walks a connection's Analyzer tree looking for the analyzer to remove, but this doesn't include `TCP_ApplicationAnalyzer`'s because those are not really in the tree, but rather are separate children of the `TCP_Analyzer`.

More generally, I keep running into problems because `Analyzer` methods don't work consistently on all subclasses of `Analyzer` - really confusing.  Either this should be regularized, or terminology adjusted so that the coder isn't misled.

### PR DESCRIPTION
**Pull request by jsiwek**
See commit message for details.
Docs need regeneration during merge.

Fixes #532

### CODE REVIEW

File: src/analyzer/protocol/tcp/TCP.cc [hunk 1]
```diff
@@ -1209,8 +1218,28 @@ void TCP_Analyzer::DeliverPacket(int len, const u_char* data, bool is_orig,
...
+		if ( child->IsFinished() || child->Removing() )
+			{
+			--i;
+
+			if ( child->Removing() )
+				child->Done();
+
+			DBG_LOG(DBG_ANALYZER, "%s deleted child %s",
+			        fmt_analyzer(this).c_str(), fmt_analyzer(child).c_str());
+			packet_children.erase(i);
```
Comment (rsmmr) [inline src/analyzer/protocol/tcp/TCP.cc]: I don't think this is safe because erasing may invalidate the iterators. However, erase() returns an iterator pointing right after the deleted argument, so if we use that then, it should be well-defined. I'll make that change.

Comment (jsiwek) [reply src/analyzer/protocol/tcp/TCP.cc]: For `std::list`: "References and iterators to the erased elements are invalidated", so think it's fine because `next` already advanced and we have no other usages of `i` after erasing it ?

(I was also mostly just copying the pattern already used several places for `Analyzer::DeleteChild` and its usages)

Comment (rsmmr) [reply src/analyzer/protocol/tcp/TCP.cc]: Ah, for some reason I thought it was a vector. Yes, for lists I think the code was fine. Anyways, the new one should work in either case.
