### PR TITLE
Fix a couple of minor issues

### LINKED ISSUE #1740: ill-formed table constructor leads to an internal error
In 4.0 (and a recent branch off Master that I also checked), the following:
> print table(3=5, 4=9);

results in:
> bad initializer (3 = 5)
fatal error in error: Type::AsTableType (error/table) (error)

### LINKED ISSUE #1741: invoking a non-hook with "hook" does not complain
I assume that this is an error, rather than intended behavior, but I'm not 100% sure.  The following script:
> function foo()
        {
        print "hi";
        }
event zeek_init()
        {
        hook foo();
        }

prints `hi` without any complaint.  I had expected that I'd be told that `foo` is not a `hook`.

### PR DESCRIPTION
**Pull request by timwoj**
- Report a better error message about table initialization needing to be a list and hide the real internal code reason why it fails
- Report an error message and bail out if the `hook` keyword is used to call something other than a hook.

Fixes #1740 
Fixes #1741

### CODE REVIEW

File: src/Expr.cc [hunk 1]
```diff
@@ -2625,10 +2625,7 @@ ValPtr AssignExpr::Eval(Frame* f) const
 TypePtr AssignExpr::InitType() const
 	{
 	if ( op1->Tag() != EXPR_LIST )
-		{
-		Error("bad initializer");
-		return nullptr;
-		}
+		Internal("bad initializer, first operand should be a list");
```
Comment (rsmmr) [inline src/Expr.cc:2628]: Why would this be an internal error? Aren't we talking about something that's triggered by incorrect script code?

Comment (timwoj) [reply src/Expr.cc]: I switched it back to being an `Error` and had `TableConstructorExpr::TableConstructorExpr` bail out if the result from initializing the type was null.

**Review by rsmmr — APPROVED** [review]
