### PR TITLE
Refactor HashKey and CompHash for consistency and to fix overflows

### LINKED ISSUE #1753: segfaults/asan errors when using set[string] in record as table key
Hello,

we've observed segfaults with Zeek 4.0 when using a script-only package.

This was tracked down to using `set[string]` in a record type which in turn is used in a state table. Very minimized example:
```
module Files_Test;

type Key: record {
  analyzers: set[string];
};

global state: table[Key] of count = {};

event Files::log_files(fi: Files::Info) {
    local k: Key;
    k$analyzers = fi$analyzers;

    state[k] = 1;
}
```

Replacing `set[string]` with `vector of string` and populating it with the values of `fi$analyzers` resolved the segfaults.

We were only able to reproduce it under live-traffic - unfortunately no simple reproducer available.

ASAN errors:

```
: =================================================================
: ==159150==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60e0000682e0 at pc 0x55b3cdce9e9f bp 0x7ffe92d7a2b0 sp 0x7ffe92d7a2a0
: WRITE of size 1 at 0x60e0000682e0 thread T0
:     #0 0x55b3cdce9e9e in zeek::detail::CompositeHash::SingleValHash(bool, char*, zeek::Type*, zeek::Val*, bool) const <...>/CompHash.cc:87
:     #1 0x55b3cdcead14 in zeek::detail::CompositeHash::SingleValHash(bool, char*, zeek::Type*, zeek::Val*, bool) const <...>/CompHash.cc:196
:     #2 0x55b3cdcf755c in zeek::detail::CompositeHash::MakeHashKey(zeek::Val const&, bool) const <...>/CompHash.cc:386
:     #3 0x55b3ce12e399 in zeek::TableVal::MakeHashKey(zeek::Val const&) const <...>/Val.cc:2822
:     #4 0x55b3ce135973 in zeek::TableVal::Find(zeek::IntrusivePtr<zeek::Val> const&) <...>/Val.cc:1973
:     #5 0x55b3cddf1c75 in zeek::detail::InExpr::Fold(zeek::Val*, zeek::Val*) const <...>/Expr.cc:4123
:     #6 0x55b3cde0a70b in zeek::detail::BinaryExpr::Eval(zeek::detail::Frame*) const <...>/Expr.cc:540
:     #7 0x55b3ce0c3f92 in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) const <...>/Stmt.cc:333
:     #8 0x55b3ce0c4b2c in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) const <...>/Stmt.cc:1563
:     #9 0x55b3ce0c4b2c in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) const <...>/Stmt.cc:1563
:     #10 0x55b3cdefd887 in zeek::detail::ScriptFunc::Invoke(std::vector<zeek::IntrusivePtr<zeek::Val>, std::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const <...>/Func.cc:404
:     #11 0x55b3cdd93efe in zeek::EventHandler::Call(std::vector<zeek::IntrusivePtr<zeek::Val>, std::allocator<zeek::IntrusivePtr<zeek::Val> > >*, bool) <...>/EventHandler.cc:110
:     #12 0x55b3cdd8f122 in zeek::Event::Dispatch(bool) <...>/Event.cc:60
:     #13 0x55b3cdd917da in zeek::EventMgr::Drain() <...>/Event.cc:190
:     #14 0x55b3ce3723e6 in zeek::file_analysis::Manager::GetFileID[abi:cxx11](zeek::analyzer::Tag const&, zeek::Connection*, bool) <...>/Manager.cc:441
:     #15 0x55b3ce375b92 in zeek::file_analysis::Manager::EndOfFile(zeek::analyzer::Tag const&, zeek::Connection*, bool) <...>/Manager.cc:175
:     #16 0x55b3ce6ee4c4 in zeek::analyzer::http::HTTP_Message::Done(bool, char const*) <...>/HTTP.cc:658
:     #17 0x55b3ce6f02a6 in zeek::analyzer::http::HTTP_Message::Done() <...>/HTTP.h:108
:     #18 0x55b3ce6f02a6 in zeek::analyzer::http::HTTP_Message::EndEntity(zeek::analyzer::mime::MIME_Entity*) <...>/HTTP.cc:729
:     #19 0x55b3ce88c739 in zeek::analyzer::mime::MIME_Entity::EndOfData() <...>/MIME.cc:671
:     #20 0x55b3ce6f82e1 in zeek::analyzer::http::HTTP_Entity::EndOfData() <...>/HTTP.cc:79
:     #21 0x55b3ce6f9c3b in zeek::analyzer::http::HTTP_Entity::Deliver(int, char const*, bool) <...>/HTTP.cc:169
:     #22 0x55b3ce6fe38c in zeek::analyzer::mime::MIME_Message::Deliver(int, char const*, bool) <...>/MIME.h:216
:     #23 0x55b3ce6f3445 in zeek::analyzer::http::HTTP_Analyzer::DeliverStream(int, unsigned char const*, bool) <...>/HTTP.cc:937
:     #24 0x55b3ce4aaf22 in zeek::analyzer::SupportAnalyzer::ForwardStream(int, unsigned char const*, bool) <...>/Analyzer.cc:895
:     #25 0x55b3ced59ecb in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliver(int, unsigned char const*) <...>/ContentLine.cc:155
:     #26 0x55b3ced581f6 in zeek::analyzer::tcp::ContentLine_Analyzer::DeliverStream(int, unsigned char const*, bool) <...>/ContentLine.cc:95
:     #27 0x55b3ce4aaa93 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) <...>/Analyzer.cc:249
:     #28 0x55b3ce4aaaa6 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) <...>/Analyzer.cc:243
:     #29 0x55b3ce4b3daf in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) <...>/Analyzer.cc:335
:     #30 0x55b3ced4cc54 in zeek::analyzer::tcp::TCP_Reassembler::Deliver(unsigned long, int, unsigned char const*) <...>/TCP_Reassembler.cc:469
:     #31 0x55b3ced54830 in zeek::analyzer::tcp::TCP_Reassembler::DeliverBlock(unsigned long, int, unsigned char const*) <...>/TCP_Reassembler.cc:628
:     #32 0x55b3ced56e08 in zeek::analyzer::tcp::TCP_Reassembler::BlockInserted(std::_Rb_tree_const_iterator<std::pair<unsigned long const, zeek::DataBlock> >) <...>/TCP_Reassembler.cc:412
:     #33 0x55b3ce053c1a in zeek::Reassembler::NewBlock(double, unsigned long, unsigned long, unsigned char const*) <...>/Reassem.cc:351
:     #34 0x55b3ced4db35 in zeek::analyzer::tcp::TCP_Reassembler::DataSent(double, unsigned long, int, unsigned char const*, zeek::analyzer::tcp::TCP_Flags, bool) <...>/TCP_Reassembler.cc:505
:     #35 0x55b3ced49bc3 in zeek::analyzer::tcp::TCP_Endpoint::DataSent(double, unsigned long, int, int, unsigned char const*, zeek::IP_Hdr const*, tcphdr const*) <...>/TCP_Endpoint.cc:200
:     #36 0x55b3ced440b9 in zeek::analyzer::tcp::TCP_Analyzer::DeliverData(double, unsigned char const*, int, int, zeek::IP_Hdr const*, tcphdr const*, zeek::analyzer::tcp::TCP_Endpoint*, unsigned long, bool, zeek::analyzer::tcp::TCP_Flags) <...>/TCP.cc:810
:     #37 0x55b3ced440b9 in zeek::analyzer::tcp::TCP_Analyzer::DeliverPacket(int, unsigned char const*, bool, unsigned long, zeek::IP_Hdr const*, int) <...>/TCP.cc:1219
:     #38 0x55b3ce4aa901 in zeek::analyzer::Analyzer::NextPacket(int, unsigned char const*, bool, unsigned long, zeek::IP_Hdr const*, int) <...>/Analyzer.cc:226
:     #39 0x55b3cdcf9de7 in zeek::Connection::NextPacket(double, bool, zeek::IP_Hdr const*, int, int, unsigned char const*&, int&, int&, zeek::Packet const*) <...>/Conn.cc:216
:     #40 0x55b3ce0a4291 in zeek::NetSessions::ProcessTransportLayer(double, zeek::Packet const*, unsigned long) <...>/Sessions.cc:231
:     #41 0x55b3cedd3a23 in zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) <...>/IP.cc:245
:     #42 0x55b3ce4868e3 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const <...>/Analyzer.cc:91
:     #43 0x55b3cedb0fa0 in zeek::packet_analysis::Ethernet::EthernetAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) <...>/Ethernet.cc:56
:     #44 0x55b3ce4868e3 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const <...>/Analyzer.cc:91
:     #45 0x55b3ce49047d in zeek::packet_analysis::Manager::ProcessPacket(zeek::Packet*) <...>/Manager.cc:111
:     #46 0x55b3ce082b39 in zeek::run_state::detail::dispatch_packet(zeek::Packet*, zeek::iosource::PktSrc*) <...>/RunState.cc:267
:     #47 0x55b3ce335be5 in zeek::iosource::PktSrc::Process() <...>/PktSrc.cc:165
:     #48 0x55b3ce080eed in zeek::run_state::detail::run_loop() <...>/RunState.cc:326
:     #49 0x55b3cd99be88 in main <...>/main.cc:59
:     #50 0x7fb9d33ee63c in __libc_start_main ..<...>/libc-start.c:314
:     #51 0x55b3cd99b879 in _start (<...>/zeek+0x460879)
: 
: 0x60e0000682e0 is located 0 bytes to the right of 160-byte region [0x60e000068240,0x60e0000682e0)
: allocated by thread T0 here:
:     #0 0x7fb9d60e5958 in operator new[](unsigned long) ..<...>/asan_new_delete.cc:82
:     #1 0x55b3cdcf71b8 in zeek::detail::CompositeHash::MakeHashKey(zeek::Val const&, bool) const <...>/CompHash.cc:369
:     #2 0x55b3ce12e399 in zeek::TableVal::MakeHashKey(zeek::Val const&) const <...>/Val.cc:2822
:     #3 0x55b3ce135973 in zeek::TableVal::Find(zeek::IntrusivePtr<zeek::Val> const&) <...>/Val.cc:1973
:     #4 0x55b3cddf1c75 in zeek::detail::InExpr::Fold(zeek::Val*, zeek::Val*) const <...>/Expr.cc:4123
:     #5 0x55b3cde0a70b in zeek::detail::BinaryExpr::Eval(zeek::detail::Frame*) const <...>/Expr.cc:540
:     #6 0x55b3ce0c3f92 in zeek::detail::ExprStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) const <...>/Stmt.cc:333
:     #7 0x55b3ce0c4b2c in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) const <...>/Stmt.cc:1563
:     #8 0x55b3ce0c4b2c in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) const <...>/Stmt.cc:1563
:     #9 0x55b3cdefd887 in zeek::detail::ScriptFunc::Invoke(std::vector<zeek::IntrusivePtr<zeek::Val>, std::allocator<zeek::IntrusivePtr<zeek::Val> > >*, zeek::detail::Frame*) const <...>/Func.cc:404
:     #10 0x55b3cdd93efe in zeek::EventHandler::Call(std::vector<zeek::IntrusivePtr<zeek::Val>, std::allocator<zeek::IntrusivePtr<zeek::Val> > >*, bool) <...>/EventHandler.cc:110
:     #11 0x55b3cdd8f122 in zeek::Event::Dispatch(bool) <...>/Event.cc:60
:     #12 0x55b3cdd917da in zeek::EventMgr::Drain() <...>/Event.cc:190
:     #13 0x55b3ce3723e6 in zeek::file_analysis::Manager::GetFileID[abi:cxx11](zeek::analyzer::Tag const&, zeek::Connection*, bool) <...>/Manager.cc:441
:     #14 0x55b3ce375b92 in zeek::file_analysis::Manager::EndOfFile(zeek::analyzer::Tag const&, zeek::Connection*, bool) <...>/Manager.cc:175
:     #15 0x55b3ce6ee4c4 in zeek::analyzer::http::HTTP_Message::Done(bool, char const*) <...>/HTTP.cc:658
:     #16 0x55b3ce6f02a6 in zeek::analyzer::http::HTTP_Message::Done() <...>/HTTP.h:108
:     #17 0x55b3ce6f02a6 in zeek::analyzer::http::HTTP_Message::EndEntity(zeek::analyzer::mime::MIME_Entity*) <...>/HTTP.cc:729
:     #18 0x55b3ce88c739 in zeek::analyzer::mime::MIME_Entity::EndOfData() <...>/MIME.cc:671
:     #19 0x55b3ce6f82e1 in zeek::analyzer::http::HTTP_Entity::EndOfData() <...>/HTTP.cc:79
:     #20 0x55b3ce6f9c3b in zeek::analyzer::http::HTTP_Entity::Deliver(int, char const*, bool) <...>/HTTP.cc:169
:     #21 0x55b3ce6fe38c in zeek::analyzer::mime::MIME_Message::Deliver(int, char const*, bool) <...>/MIME.h:216
:     #22 0x55b3ce6f3445 in zeek::analyzer::http::HTTP_Analyzer::DeliverStream(int, unsigned char const*, bool) <...>/HTTP.cc:937
:     #23 0x55b3ce4aaf22 in zeek::analyzer::SupportAnalyzer::ForwardStream(int, unsigned char const*, bool) <...>/Analyzer.cc:895
:     #24 0x55b3ced59ecb in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliver(int, unsigned char const*) <...>/ContentLine.cc:155
:     #25 0x55b3ced581f6 in zeek::analyzer::tcp::ContentLine_Analyzer::DeliverStream(int, unsigned char const*, bool) <...>/ContentLine.cc:95
:     #26 0x55b3ce4aaa93 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) <...>/Analyzer.cc:249
:     #27 0x55b3ce4aaaa6 in zeek::analyzer::Analyzer::NextStream(int, unsigned char const*, bool) <...>/Analyzer.cc:243
:     #28 0x55b3ce4b3daf in zeek::analyzer::Analyzer::ForwardStream(int, unsigned char const*, bool) <...>/Analyzer.cc:335
:     #29 0x55b3ced4cc54 in zeek::analyzer::tcp::TCP_Reassembler::Deliver(unsigned long, int, unsigned char const*) <...>/TCP_Reassembler.cc:469
:     #30 0x55b3ced54830 in zeek::analyzer::tcp::TCP_Reassembler::DeliverBlock(unsigned long, int, unsigned char const*) <...>/TCP_Reassembler.cc:628
: 
: SUMMARY: AddressSanitizer: heap-buffer-overflow <...>/CompHash.cc:87 in zeek::detail::CompositeHash::SingleValHash(bool, char*, zeek::Type*, zeek::Val*, bool) const
: Shadow bytes around the buggy address:
:   0x0c1c80005000: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
:   0x0c1c80005010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
:   0x0c1c80005020: 00 00 00 03 fa fa fa fa fa fa fa fa 00 00 00 00
:   0x0c1c80005030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04
:   0x0c1c80005040: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
: =>0x0c1c80005050: 00 00 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa
:   0x0c1c80005060: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
:   0x0c1c80005070: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
:   0x0c1c80005080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
:   0x0c1c80005090: 00 00 07 fa fa fa fa fa fa fa fa fa fa fa fa fa
:   0x0c1c800050a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
: Shadow byte legend (one shadow byte represents 8 application bytes):
:   Addressable:           00
:   Partially addressable: 01 02 03 04 05 06 07 
:   Heap left redzone:       fa
:   Freed heap region:       fd
:   Stack left redzone:      f1
:   Stack mid redzone:       f2
:   Stack right redzone:     f3
:   Stack after return:      f5
:   Stack use after scope:   f8
:   Global redzone:          f9
:   Global init order:       f6
:   Poisoned by user:        f7
:   Container overflow:      fc
:   Array cookie:            ac
:   Intra object redzone:    bb
:   ASan internal:           fe
:   Left alloca redzone:     ca
:   Right alloca redzone:    cb
: ==159150==ABORTING
```

### PR DESCRIPTION
**Pull request by ckreibich**
After looking further over the problem described in #1753 I realized that there really are a couple of things going on here:
- We have inconsistencies between computation of the size of `HashKey` buffers and writing into these buffers
- There's no bounds checking
- There's a fully separate code path for serializing values that are "singletons", i.e., where a table is indexed with only a single atomic value — this caused logic to deviate between atomic and the non-atomic scenarios. That's why you can index into a table with a record that contains a set, but not with a set directly
- I also realized that the problem in #1753 could arise any time an alignment operation after a string can "swallow" an entire other value — for example, when aligning to a `uint64_t` after a string we could also lose a 4-byte type, not just chars. So we'd need to align-up after any string by the largest possible alignment, which seems a bit ugly.

So I figured I'd rework the whole thing. This PR refactors `HashKey` and `CompositeHash`, as follows:

- It separates the memory alignment helpers into util.cc and adds unit tests. This was worthwhile because it caught a discrepancy between `SizeAlign` and `Align`/`AlignAndPad`, see the first commit.
- It broadens the `HashKey` API to allow incremental building-up of the HashKey buffer, while preserving the optimization of copying atomic values straight into the included union.
- It adds bounds-checking. The problem of #1753 would now be caught as a buffer overrun and trigger an `InternalError`.
- It removes the extra codepath for the singleton case and handles both uniformly. This gets rid of one big switch-block iterating through the various internal types. (There are now three: size estimation, writing, reading.)
- It fixes the #1753 problem by iterating over the table/set in the same order. I originally called that approach brittle, but then realized that the two codepaths of size estimation and writing happen in close proximity, so I think this is preferable. Plus, it keeps the testsuite intact. (The whole PR does not affect the testsuite atm.)
- It adds debuggability by adding a `hashkey` debug stream and `HashKey::Describe` support.

The troubleshooting I did manually at first is now available right in the `hashkey` debug stream -- for example:

```
1631581013.611697/1631581013.918509 [hashkey] HashKey 0x7a27a50 reserving 4/4: 0 -> 0 -> 4 [table-size]
1631581013.611697/1631581013.918512 [hashkey] HashKey 0x7a27a50 reserving 4/4: 4 -> 4 -> 8 [list-size]
1631581013.611697/1631581013.918514 [hashkey] HashKey 0x7a27a50 reserving 4/4: 8 -> 8 -> 12 [string-len]
1631581013.611697/1631581013.918517 [hashkey] HashKey 0x7a27a50 reserving 3/0: 12 -> 12 -> 15 [string]
1631581013.611697/1631581013.918520 [hashkey] HashKey 0x7a27a50 reserving 4/4: 15 -> 16 -> 20 [list-size]
1631581013.611697/1631581013.918523 [hashkey] HashKey 0x7a27a50 reserving 4/4: 20 -> 20 -> 24 [string-len]
1631581013.611697/1631581013.918525 [hashkey] HashKey 0x7a27a50 reserving 4/0: 24 -> 24 -> 28 [string]
1631581013.611697/1631581013.918530 [hashkey] HashKey 0x7a27a50 reserving 1/1: 28 -> 28 -> 29 [optional]
1631581013.611697/1631581013.918533 [hashkey] HashKey 0x7a27a50 reserving 4/4: 29 -> 32 -> 36 [string-len]
1631581013.611697/1631581013.918536 [hashkey] HashKey 0x7a27a50 reserving 20/0: 36 -> 36 -> 56 [string]
1631581013.611697/1631581013.918538 [hashkey] HashKey 0x7a27a50 reserving 1/1: 56 -> 56 -> 57 [optional]
1631581013.611697/1631581013.918593 [hashkey] HashKey 0x7a27a50 writing 4/4: 0 -> 0 -> 4 [table-size]
1631581013.611697/1631581013.918596 [hashkey] HashKey 0x7a27a50 writing 4/4: 4 -> 4 -> 8 [list-size]
1631581013.611697/1631581013.918599 [hashkey] HashKey 0x7a27a50 writing 4/4: 8 -> 8 -> 12 [string-len]
1631581013.611697/1631581013.918601 [hashkey] HashKey 0x7a27a50 writing 3/0: 12 -> 12 -> 15 [string]
1631581013.611697/1631581013.918604 [hashkey] HashKey 0x7a27a50 writing 4/4: 15 -> 16 -> 20 [list-size]
1631581013.611697/1631581013.918607 [hashkey] HashKey 0x7a27a50 writing 4/4: 20 -> 20 -> 24 [string-len]
1631581013.611697/1631581013.918610 [hashkey] HashKey 0x7a27a50 writing 4/0: 24 -> 24 -> 28 [string]
1631581013.611697/1631581013.918614 [hashkey] HashKey 0x7a27a50 writing 1/0: 28 -> 28 -> 29 [optional]
1631581013.611697/1631581013.918617 [hashkey] HashKey 0x7a27a50 writing 4/4: 29 -> 32 -> 36 [string-len]
1631581013.611697/1631581013.918619 [hashkey] HashKey 0x7a27a50 writing 20/0: 36 -> 36 -> 56 [string]
1631581013.611697/1631581013.918622 [hashkey] HashKey 0x7a27a50 writing 1/0: 56 -> 56 -> 57 [optional]
```

A couple of observations:

- I have not done any kind of performance benchmarking. The overall approach is essentially as before, so I'd imagine runtime is the same. But maybe I overlooked an accidental copy operation somewhere, etc.
- There's more here to optimize. For example, the serialization of patterns includes two integers that we don't actually use. I think we could also further optimize the logic that ensures sorted iteration over tables/sets (the `HashKeyComparer` stuff) by using `HashKey` buffers directly instead of going through a round of `RecreateIndex`.
- The HashKey API ended up looking rather like `SerializationFormat`, not entirely coincidentally. The next time we're happy to incorporate bigger internal changes (for 5.0, say), we should consider switching this to `SerializationFormat`. We'd break a number of tests, but get rid of an entire serialization/unserialization implementation.
- This now officially allows indexing tables with anything that's serializable. The following works:

```
global g1: table[string] of count = table();
global g2: table[table[string] of count] of string;

event zeek_init()
        {
        g1["foo"] = 1;
        g1["bar"] = 2;

        g2[g1] = "oh my";

        if ( g1 in g2 )
                print g2[g1];
        }
```

We could discuss whether we _want_ this to pass ... but given how we store keys/indexes "by value", I actually think this is a good thing. I can certainly see wanting to index with sets, for example.

Resolves #1753

### CODE REVIEW

**Comment by ckreibich** [comment]
As per discussion with @rsmmr I've reordered the patches so the fix for #1753 (fda792e1e1ba8c9ea153823d3507ec602c921d93) comes first. That way we can cherry-pick it in isolation into the next point release.

File: src/Hash.cc [hunk 1]
```diff
@@ -206,16 +197,273 @@ void* HashKey::TakeKey()
...
 
-hash_t HashKey::HashBytes(const void* bytes, int size)
+hash_t HashKey::HashBytes(const void* bytes, size_t size)
 	{
 	return KeyedHash::Hash64(bytes, size);
 	}
 
+void HashKey::Set(bool b)
+	{
+	Set(b);
```
Comment (timwoj) [inline src/Hash.cc:248]: Should this be `Set(static_cast<int>(b))`?

File: src/Hash.cc [hunk 2]
```diff
@@ -206,16 +197,273 @@ void* HashKey::TakeKey()
...
+	if ( ! IsAllocated() )
+		{
+		Set(d);
+		return;
+		}
+
+	Write(tag, &d, sizeof(d), align ? sizeof(d) : 0);
+	}
+
+void HashKey::Write(const char* tag, const void *bytes, size_t n, size_t alignment)
```
Comment (timwoj) [inline src/Hash.cc:387]: Is `tag` intentionally unused here? Same question for `SkipWrite`, `Read`, and `SkipRead` below. This has follow-on effects for the other `Write`, etc methods.

**Review by timwoj — CHANGES_REQUESTED** [review]

File: src/CompHash.cc [hunk 3]
```diff
@@ -17,6 +17,43 @@
...
+// A comparison callable to assist with consistent iteration order over tables
+// during reservation & writes.
+struct HashKeyComparer {
+	bool operator()(const std::unique_ptr<HashKey>& a, const std::unique_ptr<HashKey>& b) const
+	{
+	if ( a->Hash() != b->Hash() )
+		return a->Hash() < b->Hash();
+	if ( a->Size() != b->Size() )
+		return a->Size() < b->Size();
+	return strncmp(static_cast<const char*>(a->Key()),
```
[the remark this answers is not in the document]
Comment (ckreibich) [reply src/CompHash.cc:29]: Yeah agree — this is just the old code, unmodified. Will do.

File: src/Hash.cc (hunk 1 above)
Comment (ckreibich) [reply src/Hash.cc:248]: Thanks for spotting this — I noticed yesterday because I ended up calling this and ... yeah. It's an edit bug from a version of the code I had earlier that indeed was casting. Since I ended up added `bool` support all the way through into the `key_u` union, I was thinking of making it similar to the other ones, i.e.:

```
void HashKey::Set(bool b)
        {
        key_u.b = b;
        key = reinterpret_cast<char*>(&key_u);
        size = sizeof(b);
        }
```

File: src/Hash.cc (hunk 2 above)
Comment (ckreibich) [reply src/Hash.cc:387]: Quick recap here for anyone reading since Tim and I discussed in person: this mirrors the use of tagging as a troubleshooting aid in `SerializationFormat`. The tags (short, static strings) are only used in debug-stream log output, but remain in production builds.

Comment (ckreibich) [reply src/Hash.cc:387]: I will clarify that in a comment.

**Comment by ckreibich** [comment]
Okay Tim, this should include all updates discussed. I also added a few btests.

**Comment by ckreibich** [comment]
The recent rounds of force-pushes were to see what it takes to get the testsuite to be stable in the sanitizer build, which is the only one failing. The set of failing tests keep changing, some succeeding on retry, and they mostly seem to be cases where `btest` runs stuff in the background. I have an identical sanitizer build on my machine where the whole thing consistently runs fine. I'm wondering whether Cirrus doesn't schedule the containers continuously and delays can somehow trip up btest's monitoring ... but that's a wild guess. It doesn't seem to be about running out of memory at this point.

**Comment by ckreibich** [comment]
In the last change I brought the btest-level parallelism back down to the previous level, which has relieved some memory pressure. It seems to have worked ... I'll re-run a few times to see.

File: src/Hash.cc [hunk 4]
```diff
@@ -222,16 +212,289 @@ void* HashKey::TakeKey()
...
+void HashKey::Set(uint32_t u)
+	{
+	key_u.u32 = u;
+	key = reinterpret_cast<char*>(&key_u);
+	size = write_size = sizeof(u);
+	}
+
+void HashKey::Set(double d)
+	{
+		union {
```
Comment (timwoj) [inline src/Hash.cc:298]: What exactly does this union do?

**Review by timwoj — APPROVED** [review]
One minor question, but looks good to me otherwise.

File: src/Hash.cc (hunk 4 above)
Comment (ckreibich) [reply src/Hash.cc:298]: I wasn't sure either — I kept it as in the existing code, where it's in the constructor: https://github.com/zeek/zeek/blob/master/src/Hash.cc#L142-L145 ... which has been there for a long time. It seems safe to discard.
