### PR TITLE
Fix a couple cases where `&optional` should be rejected

### LINKED ISSUE #4639: `&optional` is allowed in places other than record fields
Via @bbannier [in Slack](https://zeekorg.slack.com/archives/CTGDG83B8/p1750150055578199): the following uses of `&optional` parse correctly, seemingly due to missing validation. I see no other uses in our tests our in the commit history. @timwoj removed the use for globals way back in 2.6.

```
# global a: int &optional; # ERROR: &optional is not valid for global variables

# Declaration accepted, but unclear how to call this.
function f(a: int &optional)
	{ }

function g()
	{
	# Optional locals are also accepted, but behave unexpectedly.
	local b: int &optional;
	print b; # RUNTIME ERROR: value used but not set.
	}

event zeek_init()
	{
	g();
	}
```

### PR DESCRIPTION
**Pull request by evantypanski**
Fixes #4639 

this just fixes a couple cases where `&optional` could apply, even though it shouldn't (since it does nothing). Namely, docs and everywhere else seem to assume it can only apply in records, so take that stance.

I also came across function parameters pretending to be records, so I carved out an exception for them in the second commit so they can get validated too. I came across [this test](https://github.com/zeek/zeek/blob/a2680d5eca180813cd264942ce9463c7bf6058b6/testing/btest/language/table-init-attrs.zeek#L46-L52) when weighing options and frantically backpedaled to the simplest solution.

Really we should have stronger attribute validation all around, but I stopped short since I just wanted to get a quick fix in for now. I've got bigger fish to fry :)

### CODE REVIEW

File: src/Attr.h [hunk 1]
```diff
@@ -108,8 +108,14 @@ class Attr final : public Obj {
 // Manages a collection of attributes.
 class Attributes final : public Obj {
 public:
-    Attributes(std::vector<AttrPtr> a, TypePtr t, bool in_record, bool is_global);
-    Attributes(TypePtr t, bool in_record, bool is_global);
+    Attributes(std::vector<AttrPtr> a, TypePtr t, bool in_record, bool is_global, bool is_param);
```
Comment (awelzel) [inline src/Attr.h:111]: I'm probably already staring at this for too long.. three trailing bools is certainly very Zeek-style, but I'm wondering if we could avoid that? This is in `detail::`, so we have some room.

Are `in_record`, `is_global` and `is_param` mutually exclusive? Or at least `in_record` and `is_param`?

I wonder if we could go for:
```
enum class AttributeLocation: uint8_t {   // or maybe AttributeScope ?
    Global,
    RecordField,
    Parameter,
};

Attributes(std::vector<AttrPtr> a, TypePtr t, AttributeLocation loc);

// or the following, but that doesn't quite click...
Attributes(std::vector<AttrPtr> a, TypePtr t, bool is_global, AttributeLocation loc);
```

If that's just opening a can of worms, say so, can certainly live with an extra bool parameter, too :-)

Comment (evantypanski) [reply src/Attr.h:111]: sure, I like the enum better but I was trying to be less intrusive :) let me know what you think. Changed the name to `AttributeTarget` (ie the type of thing the attribute is targeting). Not sure about the `General` name in there, though

(btw there is one place that `in_record` and `is_global` may not be mutually exclusive, but I'm like 99% sure it won't practically matter or that's a subtle bug/inconsistency)

Comment (awelzel) [reply src/Attr.h:111]: > (btw there is one place that in_record and is_global may not be mutually exclusive, but I'm like 99% sure it won't practically matter or that's a subtle bug/inconsistency)

I think I had seen that as well, but that seemed weird.

Comment (evantypanski) [reply src/Attr.h:111]: I dropped the commit off since there are a few extra style points that I don't want to spend too long on for now, but here's the patch that started it if it's interesting for future work:

<details> 
  <summary>attr-target-enum.diff</summary>

```
diff --git c/src/Attr.cc w/src/Attr.cc
index 9a8aa3396..3d6c81ad5 100644
--- c/src/Attr.cc
+++ w/src/Attr.cc
@@ -166,8 +166,7 @@ detail::TraversalCode Attr::Traverse(detail::TraversalCallback* cb) const {
     HANDLE_TC_ATTR_POST(tc);
 }
 
-Attributes::Attributes(std::vector<AttrPtr> a, TypePtr t, bool in_record, bool is_global, bool is_param)
-    : type(std::move(t)), in_record(in_record), global_var(is_global), is_param(is_param) {
+Attributes::Attributes(std::vector<AttrPtr> a, TypePtr t, AttributeTarget target) : type(std::move(t)), target(target) {
     attrs.reserve(a.size());
 
     SetLocationInfo(&start_location, &end_location);
@@ -232,7 +231,7 @@ void Attributes::AddAttr(AttrPtr attr, bool is_redef) {
     }
 
     // For DEFAULT, add an implicit OPTIONAL if it's not a global.
-    if ( ! global_var && attr->Tag() == ATTR_DEFAULT && ! Find(ATTR_OPTIONAL) ) {
+    if ( target != AttributeTarget::Global && attr->Tag() == ATTR_DEFAULT && ! Find(ATTR_OPTIONAL) ) {
         auto a = make_intrusive<Attr>(ATTR_OPTIONAL);
         attrs.emplace_back(std::move(a));
     }
@@ -293,7 +292,7 @@ bool Attributes::CheckAttr(Attr* a) {
         case ATTR_IS_USED: break;
 
         case ATTR_OPTIONAL:
-            if ( ! in_record )
+            if ( target != AttributeTarget::RecordField )
                 return AttrError("&optional is only valid for record fields");
 
             if ( Find(ATTR_DEFAULT) )
@@ -327,7 +326,7 @@ bool Attributes::CheckAttr(Attr* a) {
                 return AttrError("&default and &default_insert cannot be used together");
 
             std::string err_msg;
-            if ( ! check_default_attr(a, type, global_var, in_record || is_param, err_msg) && ! err_msg.empty() )
+            if ( ! check_default_attr(a, type, target, err_msg) && ! err_msg.empty() )
                 return AttrError(err_msg.c_str());
             break;
         }
@@ -336,11 +335,11 @@ bool Attributes::CheckAttr(Attr* a) {
             if ( Find(ATTR_DEFAULT_INSERT) )
                 return AttrError("&default and &default_insert cannot be used together");
 
-            if ( in_record && Find(ATTR_OPTIONAL) )
+            if ( target == AttributeTarget::RecordField && Find(ATTR_OPTIONAL) )
                 return AttrError("Using &default and &optional together results in &default behavior");
 
             std::string err_msg;
-            if ( ! check_default_attr(a, type, global_var, in_record || is_param, err_msg) && ! err_msg.empty() )
+            if ( ! check_default_attr(a, type, target, err_msg) && ! err_msg.empty() )
                 return AttrError(err_msg.c_str());
             break;
         }
@@ -439,9 +438,8 @@ bool Attributes::CheckAttr(Attr* a) {
         } break;
 
         case ATTR_BACKEND: {
-            if ( ! global_var || type->Tag() != TYPE_TABLE )
+            if ( target != AttributeTarget::Global || type->Tag() != TYPE_TABLE )
                 return AttrError("&backend only applicable to global sets/tables");
-
             // cannot do better equality check - the Broker types are not
             // actually existing yet when we are here. We will do that
             // later - before actually attaching to a broker store
@@ -582,17 +580,19 @@ bool Attributes::operator==(const Attributes& other) const {
     return true;
 }
 
-bool check_default_attr(Attr* a, const TypePtr& type, bool global_var, bool record_like, std::string& err_msg) {
+bool check_default_attr(Attr* a, const TypePtr& type, AttributeTarget target, std::string& err_msg) {
     ASSERT(a->Tag() == ATTR_DEFAULT || a->Tag() == ATTR_DEFAULT_INSERT);
     std::string aname = attr_name(a->Tag());
     // &default is allowed for global tables, since it's used in
     // initialization of table fields. It's not allowed otherwise.
-    if ( global_var && ! type->IsTable() ) {
+    if ( target == AttributeTarget::Global && ! type->IsTable() ) {
         err_msg = aname + " is not valid for global variables except for tables";
         return false;
     }
 
     const auto& atype = a->GetExpr()->GetType();
+    // Whether this should act like record initialization in certain contexts
+    auto record_like = target == AttributeTarget::RecordField || target == AttributeTarget::Parameter;
 
     if ( type->Tag() != TYPE_TABLE || (type->IsSet() && ! record_like) ) {
         if ( same_type(atype, type) )
diff --git c/src/Attr.h w/src/Attr.h
index 15cb471c2..47819fd36 100644
--- c/src/Attr.h
+++ w/src/Attr.h
@@ -105,17 +105,14 @@ protected:
     ExprPtr expr;
 };
 
+// What kind of declaration this attribute applies to.
+enum class AttributeTarget : uint8_t { Global, RecordField, Parameter, General };
+
 // Manages a collection of attributes.
 class Attributes final : public Obj {
 public:
-    Attributes(std::vector<AttrPtr> a, TypePtr t, bool in_record, bool is_global, bool is_param);
-
-    Attributes(TypePtr t, bool in_record, bool is_global)
-        : Attributes(std::vector<AttrPtr>{}, std::move(t), in_record, is_global, false) {}
-
-    Attributes(std::vector<AttrPtr> a, TypePtr t, bool in_record, bool is_global)
-        : Attributes(a, std::move(t), in_record, is_global, false) {}
-
+    Attributes(std::vector<AttrPtr> a, TypePtr t, AttributeTarget target);
+    Attributes(TypePtr t, AttributeTarget target) : Attributes(std::vector<AttrPtr>{}, std::move(t), target) {}
 
     ~Attributes() override = default;
 
@@ -146,9 +143,7 @@ protected:
     TypePtr type;
     std::vector<AttrPtr> attrs;
 
-    bool in_record;
-    bool global_var;
-    bool is_param;
+    AttributeTarget target;
 };
 
 // Checks whether default attribute "a" is compatible with the given type.
@@ -159,7 +154,7 @@ protected:
 // Returns true on compatibility (which might include modifying "a"), false
 // on an error.  If an error message hasn't been directly generated, then
 // it will be returned in err_msg.
-extern bool check_default_attr(Attr* a, const TypePtr& type, bool global_var, bool in_record, std::string& err_msg);
+extern bool check_default_attr(Attr* a, const TypePtr& type, AttributeTarget target, std::string& err_msg);
 
 // Returns the script-level name associated with an attribute, e.g. "&default".
 extern const char* attr_name(AttrTag t);
diff --git c/src/Expr.cc w/src/Expr.cc
index a0e076443..e7636fe27 100644
--- c/src/Expr.cc
+++ w/src/Expr.cc
@@ -3236,7 +3236,7 @@ TableConstructorExpr::TableConstructorExpr(ListExprPtr constructor_list,
     }
 
     if ( arg_attrs )
-        SetAttrs(make_intrusive<Attributes>(std::move(*arg_attrs), type, false, false));
+        SetAttrs(make_intrusive<Attributes>(std::move(*arg_attrs), type, AttributeTarget::General));
     else
         SetAttrs(arg_attrs2);
 
@@ -3378,7 +3378,7 @@ SetConstructorExpr::SetConstructorExpr(ListExprPtr constructor_list, std::unique
         SetError("values in set(...) constructor do not specify a set");
 
     if ( arg_attrs )
-        SetAttrs(make_intrusive<Attributes>(std::move(*arg_attrs), type, false, false));
+        SetAttrs(make_intrusive<Attributes>(std::move(*arg_attrs), type, AttributeTarget::General));
     else
         SetAttrs(std::move(arg_attrs2));
 
@@ -4876,7 +4876,7 @@ ExprPtr check_and_promote_expr(ExprPtr e, TypePtr t) {
 
                 if ( def ) {
                     std::string err_msg;
-                    if ( ! check_default_attr(def.get(), t, false, false, err_msg) ) {
+                    if ( ! check_default_attr(def.get(), t, AttributeTarget::General, err_msg) ) {
                         if ( ! err_msg.empty() )
                             t->Error(err_msg.c_str(), e.get());
                         return nullptr;
diff --git c/src/ID.cc w/src/ID.cc
index 0e2f7575a..d762107ab 100644
--- c/src/ID.cc
+++ w/src/ID.cc
@@ -225,7 +225,7 @@ void ID::UpdateValAttrs() {
                 TypeDecl* fd = rt->FieldDecl(i);
 
                 if ( ! fd->attrs )
-                    fd->attrs = make_intrusive<Attributes>(rt->GetFieldType(i), true, IsGlobal());
+                    fd->attrs = make_intrusive<Attributes>(rt->GetFieldType(i), AttributeTarget::RecordField);
 
                 fd->attrs->AddAttr(make_intrusive<Attr>(ATTR_LOG));
             }
@@ -270,7 +270,8 @@ std::string ID::GetDeprecationWarning() const {
 
 void ID::AddAttr(AttrPtr a, bool is_redef) {
     std::vector<AttrPtr> attrv{std::move(a)};
-    auto attrs = make_intrusive<Attributes>(std::move(attrv), GetType(), false, IsGlobal());
+    auto target = IsGlobal() ? AttributeTarget::Global : AttributeTarget::General;
+    auto attrs = make_intrusive<Attributes>(std::move(attrv), GetType(), target);
     AddAttrs(std::move(attrs), is_redef);
 }
 
diff --git c/src/Type.cc w/src/Type.cc
index 2d96f636e..8187df122 100644
--- c/src/Type.cc
+++ w/src/Type.cc
@@ -1267,9 +1267,7 @@ TableValPtr RecordType::GetRecordFieldsVal(const RecordVal* rv) const {
     static auto record_field = id::find_type<RecordType>("record_field");
     static auto record_field_table = id::find_type<TableType>("record_field_table");
 
-    auto attrs = zeek::make_intrusive<detail::Attributes>(record_field_table,
-                                                          /*in_record=*/false,
-                                                          /*is_global=*/false);
+    auto attrs = zeek::make_intrusive<detail::Attributes>(record_field_table, detail::AttributeTarget::General);
     attrs->AddAttr(make_intrusive<detail::Attr>(detail::ATTR_ORDERED));
     auto rval = make_intrusive<TableVal>(record_field_table, std::move(attrs));
 
@@ -1322,7 +1320,7 @@ void RecordType::AddFieldsDirectly(const type_decl_list& others, bool add_log_at
     for ( const auto& td : others ) {
         if ( add_log_attr ) {
             if ( ! td->attrs )
-                td->attrs = make_intrusive<detail::Attributes>(td->type, true, false);
+                td->attrs = make_intrusive<detail::Attributes>(td->type, detail::AttributeTarget::RecordField);
 
             td->attrs->AddAttr(make_intrusive<detail::Attr>(detail::ATTR_LOG));
         }
@@ -2367,7 +2365,7 @@ TypePtr merge_record_types(const Type* t1, const Type* t2) {
         auto td2_offset_i = rt2->FieldOffset(rt1->FieldName(i));
 
         TypePtr tdl3_i;
-        auto attrs3 = make_intrusive<detail::Attributes>(nullptr, true, false);
+        auto attrs3 = make_intrusive<detail::Attributes>(nullptr, detail::AttributeTarget::RecordField);
 
         if ( td1->attrs )
             attrs3->AddAttrs(td1->attrs);
@@ -2404,7 +2402,7 @@ TypePtr merge_record_types(const Type* t1, const Type* t2) {
         auto td1_offset_i = rt1->FieldOffset(rt2->FieldName(i));
 
         if ( td1_offset_i < 0 ) {
-            auto attrs3 = make_intrusive<detail::Attributes>(nullptr, true, false);
+            auto attrs3 = make_intrusive<detail::Attributes>(nullptr, detail::AttributeTarget::RecordField);
             if ( td2->attrs )
                 attrs3->AddAttrs(td2->attrs);
 
diff --git c/src/Val.cc w/src/Val.cc
index 9214866c5..7facc184b 100644
--- c/src/Val.cc
+++ w/src/Val.cc
@@ -2803,7 +2803,7 @@ ValPtr TableVal::DoClone(CloneState* state) {
     // is initialized ordered.
     detail::AttributesPtr init_attrs = nullptr;
     if ( auto ordered_attr = GetAttr(detail::ATTR_ORDERED) ) {
-        init_attrs = zeek::make_intrusive<detail::Attributes>(table_type, false, false);
+        init_attrs = zeek::make_intrusive<detail::Attributes>(table_type, detail::AttributeTarget::General);
         init_attrs->AddAttr(ordered_attr);
     }
 
diff --git c/src/Var.cc w/src/Var.cc
index 6e9a74a75..d8dcb0654 100644
--- c/src/Var.cc
+++ w/src/Var.cc
@@ -245,8 +245,10 @@ static void make_var(const IDPtr& id, TypePtr t, InitClass c, ExprPtr init, std:
 
     id->SetType(t);
 
-    if ( attr )
-        id->AddAttrs(make_intrusive<Attributes>(std::move(*attr), t, false, id->IsGlobal()), dt == VAR_REDEF);
+    if ( attr ) {
+        auto target = id->IsGlobal() ? AttributeTarget::Global : AttributeTarget::General;
+        id->AddAttrs(make_intrusive<Attributes>(std::move(*attr), t, target), dt == VAR_REDEF);
+    }
 
     if ( init ) {
         switch ( init->Tag() ) {
@@ -402,7 +404,7 @@ void add_type(ID* id, TypePtr t, std::unique_ptr<std::vector<AttrPtr>> attr) {
     id->MakeType();
 
     if ( attr )
-        id->SetAttrs(make_intrusive<Attributes>(std::move(*attr), tnew, false, false));
+        id->SetAttrs(make_intrusive<Attributes>(std::move(*attr), tnew, AttributeTarget::General));
 }
 
 static std::set<std::string> all_module_names;
@@ -426,7 +428,7 @@ static void transfer_arg_defaults(RecordType* args, RecordType* recv) {
 
         if ( ! recv_i->attrs ) {
             std::vector<AttrPtr> a{def};
-            recv_i->attrs = make_intrusive<Attributes>(std::move(a), recv_i->type, true, false);
+            recv_i->attrs = make_intrusive<Attributes>(std::move(a), recv_i->type, AttributeTarget::RecordField);
         }
 
         else if ( ! recv_i->attrs->Find(ATTR_DEFAULT) )
diff --git c/src/parse.y w/src/parse.y
index ea4fc7ae2..ce1bbee2b 100644
--- c/src/parse.y
+++ w/src/parse.y
@@ -212,7 +212,7 @@ static void parse_redef_record_field(ID* id, const char* field, InitClass ic,
     auto decl = rt->FieldDecl(idx);
     if ( ! decl->attrs )
         if ( ic == INIT_EXTRA )
-            decl->attrs = make_intrusive<detail::Attributes>(decl->type, true /* in_record */, false /* is_global */);
+            decl->attrs = make_intrusive<detail::Attributes>(decl->type, AttributeTarget::RecordField);
 
     for ( const auto& attr : *attrs ) {
         // At this point, only support &log redef'ing.
@@ -257,11 +257,11 @@ static void extend_record(ID* id, std::unique_ptr<type_decl_list> fields, std::u
     }
 }
 
-static AttributesPtr make_attributes(std::vector<AttrPtr>* attrs, TypePtr t, bool in_record, bool is_param) {
+static AttributesPtr make_attributes(std::vector<AttrPtr>* attrs, TypePtr t, AttributeTarget target) {
     if ( ! attrs )
         return nullptr;
 
-    auto rval = make_intrusive<Attributes>(std::move(*attrs), std::move(t), in_record, /*is_global=*/false, is_param);
+    auto rval = make_intrusive<Attributes>(std::move(*attrs), std::move(t), target);
     delete attrs;
     return rval;
 }
@@ -1296,7 +1296,8 @@ type_decl:
 		TOK_ID ':' type opt_attr ';'
 			{
 			set_location(@1, @4);
-			auto attrs = make_attributes($4, {NewRef{}, $3}, in_record > 0, /*is_param=*/false);
+            auto target = in_record > 0 ? AttributeTarget::RecordField : AttributeTarget::General;
+			auto attrs = make_attributes($4, {NewRef{}, $3}, target);
 			$$ = new TypeDecl($1, {AdoptRef{}, $3}, std::move(attrs));
 
 			if ( in_record > 0 && cur_decl_type_id )
@@ -1327,7 +1328,7 @@ formal_args_decl:
 		TOK_ID ':' type opt_attr
 			{
 			set_location(@1, @4);
-			auto attrs = make_attributes($4, {NewRef{}, $3}, /*in_record=*/false, /*is_param=*/true);
+			auto attrs = make_attributes($4, {NewRef{}, $3}, AttributeTarget::Parameter);
 			$$ = new TypeDecl($1, {AdoptRef{}, $3}, std::move(attrs));
 			}
 	;
diff --git c/src/script_opt/CPP/RuntimeInits.cc w/src/script_opt/CPP/RuntimeInits.cc
index 6bd6a1011..e8188a9a8 100644
--- c/src/script_opt/CPP/RuntimeInits.cc
+++ w/src/script_opt/CPP/RuntimeInits.cc
@@ -211,7 +211,7 @@ void CPP_IndexedInits<T>::Generate(InitsManager* im, std::vector<AttributesPtr>&
     for ( auto& iv : init_vals )
         a_list.emplace_back(im->Attrs(iv));
 
-    ivec[offset] = make_intrusive<Attributes>(a_list, nullptr, false, false);
+    ivec[offset] = make_intrusive<Attributes>(a_list, nullptr, AttributeTarget::General);
 }
 
 // Instantiate the templates we'll need.
diff --git c/src/script_opt/CPP/RuntimeOps.cc w/src/script_opt/CPP/RuntimeOps.cc
index 03973a2e7..28909f923 100644
--- c/src/script_opt/CPP/RuntimeOps.cc
+++ w/src/script_opt/CPP/RuntimeOps.cc
@@ -208,7 +208,7 @@ AttributesPtr build_attrs__CPP(IntVec attr_tags, vector<ValPtr> attr_vals) {
         attrs.emplace_back(make_intrusive<Attr>(t_i, e));
     }
 
-    return make_intrusive<Attributes>(std::move(attrs), nullptr, false, false);
+    return make_intrusive<Attributes>(std::move(attrs), nullptr, AttributeTarget::General);
 }
 
 TableValPtr set_constructor__CPP(vector<ValPtr> elements, TableTypePtr t, vector<int> attr_tags,
diff --git c/src/spicy/runtime-support.cc w/src/spicy/runtime-support.cc
index 6631a4b65..881bd5c49 100644
--- c/src/spicy/runtime-support.cc
+++ w/src/spicy/runtime-support.cc
@@ -155,7 +155,7 @@ TypePtr rt::create_record_type(const std::string& ns, const std::string& id,
     auto decls = std::make_unique<type_decl_list>();
 
     for ( const auto& f : fields ) {
-        auto attrs = make_intrusive<::zeek::detail::Attributes>(nullptr, true, false);
+        auto attrs = make_intrusive<::zeek::detail::Attributes>(nullptr, ::zeek::detail::AttributeTarget::RecordField);
 
         if ( f.is_optional ) {
             auto optional_ = make_intrusive<::zeek::detail::Attr>(::zeek::detail::ATTR_OPTIONAL);
```
</details>

**Comment by awelzel** [comment]
Chatted with Evan and the enum opened a bit of a can of worms, so going with the bool approach for now seems fine.
