### PR TITLE
plugins: Reject dynamic plugins matching names of built-in ones

### LINKED ISSUE #2403: heap-use-after-free when builtin plugin is also installed into `lib/plugins`
Somewhere in the corner of asking for trouble: When building Zeek with AF_Packet support builtin (#2401) and then also building and installing the plugin externally, there's a `heap-user-after-free` triggered on shutdown. There may be some other confusion going on (for example, `zeek -N` reports it as being dynamic twice).

Unsure it's very important, but leaving a note in case someone tries it.

```
$ zeek  -N                                                                                                                                                                                                       
...
warning in /home/awelzel/corelight-oss/zeek/build/scripts/builtin-plugins/Zeek_AF_Packet/./init.zeek, line 21: Duplicate identifier documentation: AF_Packet::link_type                                                                                                 
Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version 3.2.0)
Zeek::ARP - ARP packet analyzer (built-in)                                                                                                                                                                                                                              
...
Zeek::ZIP - Generic ZIP support analyzer (built-in)
Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version 3.2.0)                                                                                                                                                                                             
=================================================================                                     
==3582814==ERROR: AddressSanitizer: heap-use-after-free on address 0x606000c97a00 at pc 0x55574188f951 bp 0x7ffd7e1d64c0 sp 0x7ffd7e1d64b8                                                                                                                              
READ of size 8 at 0x606000c97a00 thread T0                                                                                                                                                                                                                                  #0 0x55574188f950 in std::__cxx11::_List_base<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::_M_clear() /usr/include/c++/10/bits/list.tcc:74                                                                                                       
    #1 0x55574188bb64 in std::__cxx11::_List_base<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::~_List_base() /usr/include/c++/10/bits/stl_list.h:499                                                                                                     #2 0x55574188bb64 in std::__cxx11::list<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::~list() /usr/include/c++/10/bits/stl_list.h:827                                                                                                             
    #3 0x55574188bb64 in zeek::plugin::Plugin::~Plugin() ../src/plugin/Plugin.cc:265                                                                                                                                                                                        #4 0x555742ea69d6 in plugin::Zeek_AF_Packet::Plugin::~Plugin() ../auxil/zeek-af_packet-plugin/src/Plugin.h:9                                                                                                                                                        
    #5 0x7fb46e36e4d6 in __run_exit_handlers stdlib/exit.c:108                                                                                                                                                                                                              #6 0x7fb46e36e679 in __GI_exit stdlib/exit.c:139                                                                                
    #7 0x555741193228 in zeek::detail::setup(int, char**, zeek::Options*) ../src/zeek-setup.cc:855    
    #8 0x5557431343d0 in main ../src/main.cc:13                                                                                                                                                                                                                         
    #9 0x7fb46e356d09 in __libc_start_main ../csu/libc-start.c:308                                                                                
    #10 0x555740df88d9 in _start (/home/awelzel/corelight-oss/zeek/build/src/zeek+0x33388d9)                                                                                                                                                                                                                                              
0x606000c97a00 is located 0 bytes inside of 56-byte region [0x606000c97a00,0x606000c97a38)                                          
freed by thread T0 here:                                          
    #0 0x7fb46ecee467 in operator delete(void*, unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:172                                                                                                                                                
    #1 0x55574188f93b in __gnu_cxx::new_allocator<std::_List_node<zeek::plugin::BifItem> >::deallocate(std::_List_node<zeek::plugin::BifItem>*, unsigned long) /usr/include/c++/10/ext/new_allocator.h:133                                                              
    #2 0x55574188f93b in std::allocator_traits<std::allocator<std::_List_node<zeek::plugin::BifItem> > >::deallocate(std::allocator<std::_List_node<zeek::plugin::BifItem> >&, std::_List_node<zeek::plugin::BifItem>*, unsigned long) /usr/include/c++/10/bits/alloc_tr
aits.h:492                                                                                                                          
    #3 0x55574188f93b in std::__cxx11::_List_base<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::_M_put_node(std::_List_node<zeek::plugin::BifItem>*) /usr/include/c++/10/bits/stl_list.h:446                                                          
    #4 0x55574188f93b in std::__cxx11::_List_base<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::_M_clear() /usr/include/c++/10/bits/list.tcc:81                                                                                                       
    #5 0x55574188bb64 in std::__cxx11::_List_base<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::~_List_base() /usr/include/c++/10/bits/stl_list.h:499                                                                                                 
    #6 0x55574188bb64 in std::__cxx11::list<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::~list() /usr/include/c++/10/bits/stl_list.h:827                                                                                                             
    #7 0x55574188bb64 in zeek::plugin::Plugin::~Plugin() ../src/plugin/Plugin.cc:265                                                
    #8 0x555742ea69d6 in plugin::Zeek_AF_Packet::Plugin::~Plugin() ../auxil/zeek-af_packet-plugin/src/Plugin.h:9                                                                                                                                                        
    #9 0x7fb46e36e4d6 in __run_exit_handlers stdlib/exit.c:108                                                                      
                                                                  
previously allocated by thread T0 here:                           
    #0 0x7fb46eced647 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99                                                                                                                                                           
    #1 0x55574188ca6a in __gnu_cxx::new_allocator<std::_List_node<zeek::plugin::BifItem> >::allocate(unsigned long, void const*) /usr/include/c++/10/ext/new_allocator.h:115                                                                                            
    #2 0x55574188ca6a in std::allocator_traits<std::allocator<std::_List_node<zeek::plugin::BifItem> > >::allocate(std::allocator<std::_List_node<zeek::plugin::BifItem> >&, unsigned long) /usr/include/c++/10/bits/alloc_traits.h:460                                 
    #3 0x55574188ca6a in std::__cxx11::_List_base<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::_M_get_node() /usr/include/c++/10/bits/stl_list.h:442                                                                                                 
    #4 0x55574188ca6a in std::_List_node<zeek::plugin::BifItem>* std::__cxx11::list<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::_M_create_node<zeek::plugin::BifItem const&>(zeek::plugin::BifItem const&) /usr/include/c++/10/bits/stl_list.h:634  
    #5 0x55574188ca6a in void std::__cxx11::list<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::_M_insert<zeek::plugin::BifItem const&>(std::_List_iterator<zeek::plugin::BifItem>, zeek::plugin::BifItem const&) /usr/include/c++/10/bits/stl_list.h:1
911                                                                                                                                 
    #6 0x55574188ca6a in std::__cxx11::list<zeek::plugin::BifItem, std::allocator<zeek::plugin::BifItem> >::push_back(zeek::plugin::BifItem const&) /usr/include/c++/10/bits/stl_list.h:1212                                                                            
    #7 0x55574188ca6a in zeek::plugin::Plugin::AddBifItem(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, zeek::plugin::BifItem::Type) ../src/plugin/Plugin.cc:352                                                              
    #8 0x555742eaae4c in plugin::Zeek_AF_Packet::__bif_af_packet_init(zeek::plugin::Plugin*) src/builtin-plugins/zeek-af_packet-plugin/af_packet.bif.init.cc:18  
    #9 0x55574183db43 in zeek::plugin::Manager::InitBifs() ../src/plugin/Manager.cc:492                                                                                                                                                                                 
    #10 0x5557411925a4 in zeek::detail::setup(int, char**, zeek::Options*) ../src/zeek-setup.cc:822                                                                                                                                                                     
    #11 0x5557431343d0 in main ../src/main.cc:13                                                                                    
    #12 0x7fb46e356d09 in __libc_start_main ../csu/libc-start.c:308      
```

### PR DESCRIPTION
**Pull request by awelzel**
This goes the hard-exit on conflicts route as IMO it provides better messaging that something is wrong, rather than defaulting to something the user may not expect.

Fixes #2403

### CODE REVIEW

File: src/plugin/Manager.cc [hunk 1]
```diff
@@ -195,6 +195,23 @@ bool Manager::ActivateDynamicPluginInternal(const std::string& name, bool ok_if_
 
 	DBG_LOG(DBG_PLUGINS, "Activating plugin %s", name.c_str());
 
+	// If there's a plugin with the same name already, report an error an let
+	// the user do the conflict resolution.
+	for ( const auto& p : *all_plugins )
+		{
+		auto lower_name = util::strtolower(name);
```
Comment (timwoj) [inline src/plugin/Manager.cc:202]: Move this above the loop to avoid doing it repeatedly.

File: src/plugin/Manager.cc [hunk 2]
```diff
@@ -195,6 +195,23 @@ bool Manager::ActivateDynamicPluginInternal(const std::string& name, bool ok_if_
 
 	DBG_LOG(DBG_PLUGINS, "Activating plugin %s", name.c_str());
 
+	// If there's a plugin with the same name already, report an error an let
```
Comment (timwoj) [inline src/plugin/Manager.cc:198]: s/an/and/

**Review by timwoj — CHANGES_REQUESTED** [review]

File: src/plugin/Manager.cc (hunk 1 above)
Comment (awelzel) [reply src/plugin/Manager.cc]: Thanks, done. I was mostly concerned about the O(n^2) this ends up being, but there aren't that many plugins :crossed_fingers: and if it gets too slow we can store plugins in a lookup table I guess.

**Comment by awelzel** [comment]
Hey @timwoj - I did the changes you requested I believe. Is there something else you had expected to see?

**Review by timwoj — APPROVED** [review]
Nope, I just forgot to re-review after you made changes. Looks good to me now!

**Comment by timwoj** [comment]
If you squash the fixup commit, I'll merge it today.
