### PR TITLE
Return a warning and fail if creating a store at global scope

### LINKED ISSUE #3969: Segfault when calling `Broker::create_master` in module scope
I see segfaults when trying to call `Broker::create_master` in module scope.

I would have expected this to work, or at least be rejected with a diagnostic.

```zeek
# foo.zeek
const x = Broker::create_master("store");
global t: table[string] of count &broker_store="store";
```

```console
$ zeek -b foo.zeek
AddressSanitizer:DEADLYSIGNAL
=================================================================
==3661752==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x5d6859374d94 bp 0x7ffde5af1550 sp 0x7ffde5af1460 T0)
==3661752==The signal is caused by a READ memory access.
==3661752==Hint: address points to the zero page.
    #0 0x5d6859374d94 in std::__shared_ptr<broker::internal::endpoint_context, (__gnu_cxx::_Lock_policy)2>::operator bool() const /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/shared_ptr_base.h:1671:23
    #1 0x5d6859374d94 in bool std::operator==<broker::internal::endpoint_context>(std::shared_ptr<broker::internal::endpoint_context> const&, std::nullptr_t) /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/shared_ptr.h:561:15
    #2 0x5d6859374d94 in broker::endpoint::is_shutdown() const /zeek/auxil/broker/libbroker/broker/endpoint.hh:498:17
    #3 0x5d6859374d94 in zeek::Broker::Manager::MakeMaster(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, broker::backend, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, broker::data, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const, broker::data>>>) /zeek/src/broker/Manager.cc:1558:27
    #4 0x5d6859c6f7d1 in zeek::BifFunc::Broker::__create_master_bif(zeek::detail::Frame*, std::vector<zeek::IntrusivePtr<zeek::Val>, std::allocator<zeek::IntrusivePtr<zeek::Val>>> const*) /zeek/src/broker/store.bif:42:45
    #5 0x5d6859cd6505 in zeek::detail::BuiltinFunc::Invoke(std::vector<zeek::IntrusivePtr<zeek::Val>, std::allocator<zeek::IntrusivePtr<zeek::Val>>>*, zeek::detail::Frame*) const /zeek/src/Func.cc:741:19
    #6 0x5d6859bf90a9 in zeek::detail::CallExpr::Eval(zeek::detail::Frame*) const /zeek/src/Expr.cc:4122:22
    #7 0x5d6859de4d51 in zeek::detail::ReturnStmt::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) /zeek/src/Stmt.cc:1398:19
    #8 0x5d6859de5686 in zeek::detail::StmtList::Exec(zeek::detail::Frame*, zeek::detail::StmtFlowType&) /zeek/src/Stmt.cc:1433:29
    #9 0x5d6859cce066 in zeek::detail::ScriptFunc::Invoke(std::vector<zeek::IntrusivePtr<zeek::Val>, std::allocator<zeek::IntrusivePtr<zeek::Val>>>*, zeek::detail::Frame*) const /zeek/src/Func.cc:386:34
    #10 0x5d6859bf90a9 in zeek::detail::CallExpr::Eval(zeek::detail::Frame*) const /zeek/src/Expr.cc:4122:22
    #11 0x5d6859bd22ed in zeek::detail::AssignExpr::Eval(zeek::detail::Frame*) const /zeek/src/Expr.cc:2399:24
    #12 0x5d6859ebdb61 in zeek::detail::make_var(zeek::IntrusivePtr<zeek::detail::ID> const&, zeek::IntrusivePtr<zeek::Type>, zeek::detail::InitClass, zeek::IntrusivePtr<zeek::detail::Expr>, std::unique_ptr<std::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::allocator<zeek::IntrusivePtr<zeek::detail::Attr>>>, std::default_delete<std::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::allocator<zeek::IntrusivePtr<zeek::detail::Attr>>>>>, zeek::detail::DeclType, bool) /zeek/src/Var.cc:294:38
    #13 0x5d6859ebb79d in zeek::detail::add_global(zeek::IntrusivePtr<zeek::detail::ID> const&, zeek::IntrusivePtr<zeek::Type>, zeek::detail::InitClass, zeek::IntrusivePtr<zeek::detail::Expr>, std::unique_ptr<std::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::allocator<zeek::IntrusivePtr<zeek::detail::Attr>>>, std::default_delete<std::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::allocator<zeek::IntrusivePtr<zeek::detail::Attr>>>>>, zeek::detail::DeclType) /zeek/src/Var.cc:330:5
    #14 0x5d68596d622a in build_global(zeek::detail::ID*, zeek::Type*, zeek::detail::InitClass, zeek::detail::Expr*, std::vector<zeek::IntrusivePtr<zeek::detail::Attr>, std::allocator<zeek::IntrusivePtr<zeek::detail::Attr>>>*, zeek::detail::DeclType) /zeek/src/parse.y:326:2
    #15 0x5d68596ce04a in yyparse() /zeek/src/parse.y:1410:4
    #16 0x5d6859a84f76 in zeek::detail::setup(int, char**, zeek::Options*) /zeek/src/zeek-setup.cc:759:30
    #17 0x5d685a49ee17 in main /zeek/src/main.cc:52:25
    #18 0x7f764ce2a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #19 0x7f764ce2a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #20 0x5d685842a904 in _start (/zeek/build/src/zeek+0x86b904) (BuildId: 78558b83062baeba24a0f264c9b063cd86bc52b9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /zeek/auxil/broker/libbroker/broker/endpoint.hh:498:17 in broker::endpoint::is_shutdown() const
==3661752==ABORTING
```

This is due to us accessing `zeek::Broker::Manager::bstate` which is only set up on `InitPostScript`

https://github.com/zeek/zeek/blob/ac5522f03a765583954c41849e99bd6934769fa5/src/broker/Manager.cc#L1558

https://github.com/zeek/zeek/blob/ac5522f03a765583954c41849e99bd6934769fa5/src/broker/Manager.cc#L335

### PR DESCRIPTION
**Pull request by timwoj**
Creating the `bstate` object requires a bunch of options that aren't defined until script parsing is complete. 

Fixes #3969

### CODE REVIEW

File: src/broker/Manager.cc [hunk 1]
```diff
@@ -1582,7 +1582,14 @@ void Manager::ProcessStoreResponse(detail::StoreHandleVal* s, broker::store::res
 }
 
 detail::StoreHandleVal* Manager::MakeMaster(const string& name, broker::backend type, broker::backend_options opts) {
-    if ( bstate->endpoint.is_shutdown() )
+    if ( ! bstate ) {
```
Comment (awelzel) [inline src/broker/Manager.cc:1585]: Depending how much we want to do with broker stores, could also queue an re-run `MakeMaster` once `bstate` was initialized?

**Comment by awelzel** [comment]
I'm not sure the following is really worth it, but was going down the rabbit hole of AST traversal to pick out functions that aren't allowed or meaningful to be called from the global scope. The nice part is that one wouldn't need to actually execute scripts to get an error (think `--parse-only`)

```
+class CollectDisallowedGlobalCalls : public TraversalCallback {
+public:
+    TraversalCode PreID(const ID* id) override {
+        if ( id->HasVal() && IsFunc(id->GetVal()->GetType()->Tag()) ) // same as in Func.cc
+            id->GetVal()->AsFunc()->Traverse(this);
+
+        return TC_CONTINUE;
+    }
+
+    TraversalCode PreFunction(const zeek::Func* func) override {
+        if ( funcs.count(func) > 0 )
+            return TC_ABORTSTMT;
+
+        funcs.insert(func);
+
+        if ( disallowed.count(func->GetName()) )
+            found.insert(func->GetName());
+
+        return TC_CONTINUE;
+    }
+
+    std::set<std::string, std::less<>> found;
+    std::unordered_set<const Func*> funcs;
+    static std::unordered_set<std::string> disallowed;
+};
+
+std::unordered_set<std::string> CollectDisallowedGlobalCalls::disallowed = {
+    // Broker needs to go through InitPostScript(), so cannot
+    // call in global scope.
+    "Broker::create_master",
+
+    // There's no packet at global scope.
+    "get_current_packet",
+    "get_current_packet_ts",
+    "get_current_packet_header",
+
+    // Only useful within event handlers.
+    "current_analyzer",
+
+};
+
+
+// Validate that there are no direct or indirect calls to
+// functions that require either events or a InitPostScript()
+// setup.
+class GlobalFuncCallValidator : public TraversalCallback {
+public:
+    TraversalCode PreFunction(const zeek::Func* func) override {
+        ++func_depth;
+        return TC_CONTINUE;
+    }
+
+    TraversalCode PostFunction(const zeek::Func* func) override {
+        func_depth--;
+        return TC_CONTINUE;
+    }
+
+    TraversalCode PreExpr(const zeek::detail::Expr* e) override {
+        if ( func_depth > 0 ) // Ignore non-global expressions.
+            return TC_ABORTSTMT;
+
+        if ( e->Tag() != EXPR_CALL )
+            return TC_CONTINUE;
+
+        const auto* ce = e->AsCallExpr();
+
+        CollectDisallowedGlobalCalls cdg_cb;
+        ce->Traverse(&cdg_cb);
+
+        if ( ! cdg_cb.found.empty() ) {
+            std::string names;
+            for ( const auto& n : cdg_cb.found ) {
+                if ( ! names.empty() )
+                    names += ", ";
+                names += n;
+            }
+
+            const auto* s = cdg_cb.found.size() > 1 ? "s" : "";
+            ce->Error(zeek::util::fmt("function%s %s may be called directly or indirectly from global scope", s,
+                                      names.c_str()));
+        }
+        return TC_CONTINUE;
+    }
+
+    int func_depth = 0;
+};
+
+
 void script_validation() {
     BreakNextScriptValidation bn_cb(true);
     traverse_all(&bn_cb);
+
+    GlobalFuncCallValidator gfc_cb;
+    traverse_all(&gfc_cb);
 }
```

File: src/broker/Manager.cc (hunk 1 above)
Comment (timwoj) [reply src/broker/Manager.cc:1585]: Would that do anything for the example given in the ticket? `MakeMaster` gets queued, but then we try to use the result of it to create a table. At the time the table gets created, the store handle is still invalid because `MakeMaster` didn't return anything. So now you not only need to queue the creation, but also the table creation.

**Comment by timwoj** [comment]
> I'm not sure the following is really worth it, but was going down the rabbit hole of AST traversal to pick out functions that aren't allowed or meaningful to be called from the global scope. 

This feels like it's getting away from the point of this PR, which was to fix the crash/asan report for a simple Zeek script. Having a system for automated traversal that determines all of the functions that can't be used in a global context would be handy but I don't see doing it as part of this.

File: src/broker/Manager.cc (hunk 1 above)
Comment (awelzel) [reply src/broker/Manager.cc:1585]: yeah, just scrolling a bit, this was a very naive suggestion.

File: src/broker/Manager.cc [hunk 2]
```diff
@@ -1582,7 +1582,14 @@ void Manager::ProcessStoreResponse(detail::StoreHandleVal* s, broker::store::res
...
+        if ( zeek::detail::current_scope() == zeek::detail::global_scope() )
+            reporter->Warning("Broker stores cannot be created at the global scope");
+
+        return nullptr;
+    }
+
+    if ( ! bstate || bstate->endpoint.is_shutdown() )
```
Comment (awelzel) [inline src/broker/Manager.cc:1592]: Redundant?

```suggestion
    if ( bstate->endpoint.is_shutdown() )
```

File: src/broker/Manager.cc [hunk 3]
```diff
@@ -1582,7 +1582,14 @@ void Manager::ProcessStoreResponse(detail::StoreHandleVal* s, broker::store::res
 }
 
 detail::StoreHandleVal* Manager::MakeMaster(const string& name, broker::backend type, broker::backend_options opts) {
-    if ( bstate->endpoint.is_shutdown() )
+    if ( ! bstate ) {
+        if ( zeek::detail::current_scope() == zeek::detail::global_scope() )
+            reporter->Warning("Broker stores cannot be created at the global scope");
```
Comment (awelzel) [inline src/broker/Manager.cc:1587]: I guess `Error()` would also be fine, but your call.

**Review by awelzel — APPROVED** [review]
