### PR TITLE
HTTP: Implement FlipRoles()

### LINKED ISSUE #3789: 6.2.1 worker crashes with zeek::analyzer::http::HTTP_Entity::Deliver(int, const char*, bool): Assertion `! trailing_CRLF' failed.
In troubleshooting https://github.com/zeek/zeek/issues/3780, I recompiled Zeek with debug symbols (correctly this time) and fairly quickly experienced two crashes.

```
Zeek 6.2.1-debug
Linux 5.15.0-107-generic

Zeek plugins: (none found)

==== No reporter.log

==== stderr.log
listening on eno1

zeek: /usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc:152: virtual void zeek::analyzer::http::HTTP_Entity::Deliver(int, const char*, bool): Assertion `! trailing_CRLF' failed.
/srv/zeek/share/zeekctl/scripts/run-zeek: line 110: 3057917 Aborted                 (core dumped) nohup ${pin_command} $pin_cpu "$myzeek" "$@"

==== stdout.log
max memory size             (kbytes, -m) unlimited
data seg size               (kbytes, -d) unlimited
virtual memory              (kbytes, -v) unlimited
core file size              (blocks, -c) unlimited

==== .cmdline
-i af_packet::eno1 -U .status -p zeekctl -p zeekctl-live -p local -p worker-barfleur-10 local.zeek zeekctl base/frameworks/cluster zeekctl/auto

==== .env_vars
PATH=/srv/zeek/bin:/srv/zeek/share/zeekctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
ZEEKPATH=/srv/zeek/spool/installed-scripts-do-not-touch/site::/srv/zeek/spool/installed-scripts-do-not-touch/auto:/srv/zeek/share/zeek:/srv/zeek/share/zeek/policy:/srv/zeek/share/zeek/site:/srv/zeek/share/zeek/builtin-plugins
CLUSTER_NODE=worker-barfleur-10

==== .status
RUNNING [run_loop]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log
```

With backtrace:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140329419130240) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140329419130240) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140329419130240, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fa0fd6c4476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fa0fd6aa7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fa0fd6aa71b in __assert_fail_base (fmt=0x7fa0fd85f130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55e8065c247f "! trailing_CRLF",
    file=0x55e8065c2420 "/usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc", line=152, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007fa0fd6bbe96 in __GI___assert_fail (assertion=0x55e8065c247f "! trailing_CRLF", file=0x55e8065c2420 "/usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc", line=152,
    function=0x55e8065c23d0 "virtual void zeek::analyzer::http::HTTP_Entity::Deliver(int, const char*, bool)") at ./assert/assert.c:101
#7  0x000055e8056dd850 in zeek::analyzer::http::HTTP_Entity::Deliver (this=0x7fa0d7f2a300, len=135,
    data=0x7fa0dc609200 "弡H\021\343\305\372h\227\f\206\372l-#\b\361{d\254t;|\234\036\353L<N\255\307G\332z\223fc\222\205\004\316#\202\277#\020\236^\004\201\241\254\222n\201́6\\\244\310\016Ӊ\024\t\204edڥ\347&\025\351\255#\341\263S\243\334\v>K\034{\006\353\vJ p~\230\027,\314/\344\255}\004\327K\331]F\237\223(:6\216/@\273-\230\317:\306Gt\377\036\031\264\275\207\251\333\035?",
    trailing_CRLF=true) at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc:152
#8  0x000055e8056e5027 in zeek::analyzer::mime::MIME_Message::Deliver (this=0x7fa0e2995500, len=135,
    data=0x7fa0dc609200 "弡H\021\343\305\372h\227\f\206\372l-#\b\361{d\254t;|\234\036\353L<N\255\307G\332z\223fc\222\205\004\316#\202\277#\020\236^\004\201\241\254\222n\201́6\\\244\310\016Ӊ\024\t\204edڥ\347&\025\351\255#\341\263S\243\334\v>K\034{\006\353\vJ p~\230\027,\314/\344\255}\004\327K\331]F\237\223(:6\216/@\273-\230\317:\306Gt\377\036\031\264\275\207\251\333\035?",
    trailing_CRLF=true) at /usr/local/src/zeek-6.2.1/src/include/zeek/analyzer/protocol/mime/MIME.h:211
#9  0x000055e8056e1432 in zeek::analyzer::http::HTTP_Analyzer::DeliverStream (this=0x7fa0e58e6a00, len=135,
    data=0x7fa0dc609200 "弡H\021\343\305\372h\227\f\206\372l-#\b\361{d\254t;|\234\036\353L<N\255\307G\332z\223fc\222\205\004\316#\202\277#\020\236^\004\201\241\254\222n\201́6\\\244\310\016Ӊ\024\t\204edڥ\347&\025\351\255#\341\263S\243\334\v>K\034{\006\353\vJ p~\230\027,\314/\344\255}\004\327K\331]F\237\223(:6\216/@\273-\230\317:\306Gt\377\036\031\264\275\207\251\333\035?", is_orig=false)
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc:941
#10 0x000055e8055c8bc8 in zeek::analyzer::SupportAnalyzer::ForwardStream (this=0x7fa0e2f7c900, len=135,
    data=0x7fa0dc609200 "弡H\021\343\305\372h\227\f\206\372l-#\b\361{d\254t;|\234\036\353L<N\255\307G\332z\223fc\222\205\004\316#\202\277#\020\236^\004\201\241\254\222n\201́6\\\244\310\016Ӊ\024\t\204edڥ\347&\025\351\255#\341\263S\243\334\v>K\034{\006\353\vJ p~\230\027,\314/\344\255}\004\327K\331]F\237\223(:6\216/@\273-\230\317:\306Gt\377\036\031\264\275\207\251\333\035?", is_orig=false)
    at /usr/local/src/zeek-6.2.1/src/analyzer/Analyzer.cc:747
#11 0x000055e805b943a7 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliverOnce (this=0x7fa0e2f7c900, len=464,
    data=0x7fa0e1043812 "\rr\343\342\071M\247}\r\237Z\232\244\037\363D\261\337[\327e+\vY\305\020\061wL\244\367S3\350B\345\v\377\265e$\026\233\355-\363#ϐBs\302\321\001\"\357\031#IA\034\271\\\357-Z\177\061g\035\233\363\240\312P\313f(\265\005^<q\247\332?\322\f\354`BN?\217L\377\236X\372\250\275)D\003\006T\267\273\202", <incomplete sequence \350>)
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/ContentLine.cc:235
#12 0x000055e805b93fd8 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliver (this=0x7fa0e2f7c900, len=599,
    data=0x7fa0e104378b "弡H\021\343\305\372h\227\f\206\372l-#\b\361{d\254t;|\234\036\353L<N\255\307G\332z\223fc\222\205\004\316#\202\277#\020\236^\004\201\241\254\222n\201́6\\\244\310\016Ӊ\024\t\204edڥ\347&\025\351\255#\341\263S\243\334\v>K\034{\006\353\vJ p~\230\027,\314/\344\255}\004\327K\331]F\237\223(:6\216/@\273-\230\317:\306Gt\377\036\031\264\275\207\251\333\035?\rr\343\342\071M\247}\r\237Z\232\244\037\363D\261\337[\327e+\vY\305\020\061wL\244\367S3\350B\345\v\377\265e$\026\233\355-\363#ϐBs\302\321\001\"\357\031#IA\034\271\\\357-"...)
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/ContentLine.cc:187
#13 0x000055e805b93b44 in zeek::analyzer::tcp::ContentLine_Analyzer::DeliverStream (this=0x7fa0e2f7c900, len=1250,
    data=0x7fa0e1043500 "HTTP/1.1 206 Partial Content\r\nAccept-Ranges: bytes\r\nCache-Control: public, max-age=17280000\r\nContent-Type: application/x-chrome-extension\r\nETag: \"rae/T/KOkpKkNnpIrgY5HpxfXWI=\"\r\nLast-Modified: Thu, 13 "..., is_orig=false) at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/ContentLine.cc:83
#14 0x000055e8055c546b in zeek::analyzer::Analyzer::NextStream (this=0x7fa0e2f7c900, len=1250,
    data=0x7fa0e1043500 "HTTP/1.1 206 Partial Content\r\nAccept-Ranges: bytes\r\nCache-Control: public, max-age=17280000\r\nContent-Type: application/x-chrome-extension\r\nETag: \"rae/T/KOkpKkNnpIrgY5HpxfXWI=\"\r\nLast-Modified: Thu, 13 "..., is_orig=false) at /usr/local/src/zeek-6.2.1/src/analyzer/Analyzer.cc:215
#15 0x000055e8055c5443 in zeek::analyzer::Analyzer::NextStream (this=0x7fa0e58e6a00, len=1250,
    data=0x7fa0e1043500 "HTTP/1.1 206 Partial Content\r\nAccept-Ranges: bytes\r\nCache-Control: public, max-age=17280000\r\nContent-Type: application/x-chrome-extension\r\nETag: \"rae/T/KOkpKkNnpIrgY5HpxfXWI=\"\r\nLast-Modified: Thu, 13 "..., is_orig=false) at /usr/local/src/zeek-6.2.1/src/analyzer/Analyzer.cc:211
#16 0x000055e8055c5981 in zeek::analyzer::Analyzer::ForwardStream (this=0x7fa0e24c7940, len=1250,
    data=0x7fa0e1043500 "HTTP/1.1 206 Partial Content\r\nAccept-Ranges: bytes\r\nCache-Control: public, max-age=17280000\r\nContent-Type: application/x-chrome-extension\r\nETag: \"rae/T/KOkpKkNnpIrgY5HpxfXWI=\"\r\nLast-Modified: Thu, 13 "..., is_orig=false) at /usr/local/src/zeek-6.2.1/src/analyzer/Analyzer.cc:283
#17 0x000055e805b92289 in zeek::analyzer::tcp::TCP_Reassembler::Deliver (this=0x7fa0d06ee400, seq=4948, len=1250,
    data=0x7fa0e1043500 "HTTP/1.1 206 Partial Content\r\nAccept-Ranges: bytes\r\nCache-Control: public, max-age=17280000\r\nContent-Type: application/x-chrome-extension\r\nETag: \"rae/T/KOkpKkNnpIrgY5HpxfXWI=\"\r\nLast-Modified: Thu, 13 "...) at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Reassembler.cc:409
#18 0x000055e805b928c6 in zeek::analyzer::tcp::TCP_Reassembler::DeliverBlock (this=0x7fa0d06ee400, seq=4948, len=1250,
    data=0x7fa0e1043500 "HTTP/1.1 206 Partial Content\r\nAccept-Ranges: bytes\r\nCache-Control: public, max-age=17280000\r\nContent-Type: application/x-chrome-extension\r\nETag: \"rae/T/KOkpKkNnpIrgY5HpxfXWI=\"\r\nLast-Modified: Thu, 13 "...) at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Reassembler.cc:546
#19 0x000055e805b91e58 in zeek::analyzer::tcp::TCP_Reassembler::BlockInserted (this=0x7fa0d06ee400,
    it={first = 4948, second = {seq = 4948, upper = 6198, block = 0x7fa0e1043500 "HTTP/1.1 206 Partial Content\r\nAccept-Ranges: bytes\r\nCache-Control: public, max-age=17280000\r\nContent-Type: application/x-chrome-extension\r\nETag: \"rae/T/KOkpKkNnpIrgY5HpxfXWI=\"\r\nLast-Modified: Thu, 13 "...}}) at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Reassembler.cc:360
#20 0x000055e8061c47ba in zeek::Reassembler::NewBlock (this=0x7fa0d06ee400, t=1718713961.1845059, seq=4948, len=1250, data=0x7fa0e8e34b50 "") at /usr/local/src/zeek-6.2.1/src/Reassem.cc:332
#21 0x000055e805b923c1 in zeek::analyzer::tcp::TCP_Reassembler::DataSent (this=0x7fa0d06ee400, t=1718713961.1845059, seq=4948, len=1250, data=0x7fa0e8e34b50 "", arg_flags=..., replaying=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Reassembler.cc:442
#22 0x000055e805b8f1df in zeek::analyzer::tcp::TCP_Endpoint::DataSent (this=0x7fa0dd4ed340, t=1718713961.1845059, seq=4948, len=1250, caplen=1250, data=0x7fa0e8e34b50 "", ip=0x7fa0e551eb90,
    tp=0x7fa0e8e34b3c) at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Endpoint.cc:173
#23 0x000055e805c15767 in zeek::packet_analysis::TCP::TCPSessionAdapter::Process (this=0x7fa0e24c7940, is_orig=false, tp=0x7fa0e8e34b3c, len=1250, ip=std::shared_ptr<zeek::IP_Hdr> (use count 2, weak count 0) = {...}, data=0x7fa0e8e34b50 "", remaining=1250) at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/tcp/TCPSessionAdapter.cc:623
#24 0x000055e805c13225 in zeek::packet_analysis::TCP::TCPAnalyzer::DeliverPacket (this=0x7fa0f69c5d50, c=0x7fa0e4f63500, t=1718713961.1845059, is_orig=false, remaining=1250, pkt=0x7fa0f6e52648) at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/tcp/TCP.cc:111
#25 0x000055e805c089ef in zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket (this=0x7fa0f69c5d50, len=1270, data=0x7fa0e8e34b3c "", pkt=0x7fa0f6e52648) at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/ip/IPBasedAnalyzer.cc:88
#26 0x000055e805bd6c2d in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x7fa0f6a4cdb0, len=1270, data=0x7fa0e8e34b3c "", packet=0x7fa0f6e52648, identifier=6) at /usr/local/src/zeek-6.2.1/src/packet_analysis/Analyzer.cc:117
#27 0x000055e805c05506 in zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket (this=0x7fa0f6a4cdb0, len=1270, data=0x7fa0e8e34b3c "", packet=0x7fa0f6e52648) at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/ip/IP.cc:265
#28 0x000055e805bd6c2d in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x7fa0fcf175d0, len=1290, data=0x7fa0e8e34b28 "", packet=0x7fa0f6e52648, identifier=2048) at /usr/local/src/zeek-6.2.1/src/packet_analysis/Analyzer.cc:117
#29 0x000055e805beaa4e in zeek::packet_analysis::Ethernet::EthernetAnalyzer::AnalyzePacket (this=0x7fa0fcf175d0, len=1304, data=0x7fa0e8e34b1a "", packet=0x7fa0f6e52648) at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/ethernet/Ethernet.cc:45
#30 0x000055e805bd6c2d in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x7fa0f6a4d530, len=1304, data=0x7fa0e8e34b1a "", packet=0x7fa0f6e52648, identifier=1) at /usr/local/src/zeek-6.2.1/src/packet_analysis/Analyzer.cc:117
#31 0x000055e805bdc58f in zeek::packet_analysis::Manager::ProcessPacket (this=0x7fa0fce7e8c0, packet=0x7fa0f6e52648) at /usr/local/src/zeek-6.2.1/src/packet_analysis/Manager.cc:116
#32 0x000055e8061d922b in zeek::run_state::detail::dispatch_packet (pkt=0x7fa0f6e52648, pkt_src=0x7fa0f6e52600) at /usr/local/src/zeek-6.2.1/src/RunState.cc:242
#33 0x000055e805dc9e35 in zeek::iosource::PktSrc::Process (this=0x7fa0f6e52600) at /usr/local/src/zeek-6.2.1/src/iosource/PktSrc.cc:120
#34 0x000055e8061d958f in zeek::run_state::detail::run_loop () at /usr/local/src/zeek-6.2.1/src/RunState.cc:289
#35 0x000055e8055c2af5 in main (argc=17, argv=0x7ffd25192418) at /usr/local/src/zeek-6.2.1/src/main.cc:93
```

And:
```
Zeek 6.2.1-debug
Linux 5.15.0-107-generic

Zeek plugins: (none found)

==== No reporter.log

==== stderr.log
listening on eno1

zeek: /usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc:152: virtual void zeek::analyzer::http::HTTP_Entity::Deliver(int, const char*, bool): Assertion `! trailing_CRLF' failed.
/srv/zeek/share/zeekctl/scripts/run-zeek: line 110: 3057934 Aborted                 (core dumped) nohup ${pin_command} $pin_cpu "$myzeek" "$@"

==== stdout.log
max memory size             (kbytes, -m) unlimited
data seg size               (kbytes, -d) unlimited
virtual memory              (kbytes, -v) unlimited
core file size              (blocks, -c) unlimited

==== .cmdline
-i af_packet::eno1 -U .status -p zeekctl -p zeekctl-live -p local -p worker-barfleur-22 local.zeek zeekctl base/frameworks/cluster zeekctl/auto

==== .env_vars
PATH=/srv/zeek/bin:/srv/zeek/share/zeekctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
ZEEKPATH=/srv/zeek/spool/installed-scripts-do-not-touch/site::/srv/zeek/spool/installed-scripts-do-not-touch/auto:/srv/zeek/share/zeek:/srv/zeek/share/zeek/policy:/srv/zeek/share/zeek/site:/srv/zeek/share/zeek/builtin-plugins
CLUSTER_NODE=worker-barfleur-22

==== .status
RUNNING [run_loop]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log
```

With backtrace:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140134267409792) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140134267409792) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140134267409792, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f738d795476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f738d77b7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f738d77b71b in __assert_fail_base (fmt=0x7f738d930130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55be635dd47f "! trailing_CRLF",
    file=0x55be635dd420 "/usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc", line=152, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007f738d78ce96 in __GI___assert_fail (assertion=0x55be635dd47f "! trailing_CRLF", file=0x55be635dd420 "/usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc", line=152,
    function=0x55be635dd3d0 "virtual void zeek::analyzer::http::HTTP_Entity::Deliver(int, const char*, bool)") at ./assert/assert.c:101
#7  0x000055be626f8850 in zeek::analyzer::http::HTTP_Entity::Deliver (this=0x7f735faee480, len=13, data=0x7f73761feb00 "\001", trailing_CRLF=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc:152
#8  0x000055be62700027 in zeek::analyzer::mime::MIME_Message::Deliver (this=0x7f73613e1570, len=13, data=0x7f73761feb00 "\001", trailing_CRLF=true)
    at /usr/local/src/zeek-6.2.1/src/include/zeek/analyzer/protocol/mime/MIME.h:211
#9  0x000055be626fc22a in zeek::analyzer::http::HTTP_Analyzer::DeliverStream (this=0x7f7372cf8800, len=13, data=0x7f73761feb00 "\001", is_orig=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/http/HTTP.cc:905
#10 0x000055be625e3bc8 in zeek::analyzer::SupportAnalyzer::ForwardStream (this=0x7f7376519a80, len=13, data=0x7f73761feb00 "\001", is_orig=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/Analyzer.cc:747
#11 0x000055be62baf3a7 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliverOnce (this=0x7f7376519a80, len=15, data=0x7f736daa25ae "\r\vYe+\220\001\002\002\375ĺ")
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/ContentLine.cc:235
#12 0x000055be62baefd8 in zeek::analyzer::tcp::ContentLine_Analyzer::DoDeliver (this=0x7f7376519a80, len=28, data=0x7f736daa25a1 "\001")
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/ContentLine.cc:187
#13 0x000055be62baeb44 in zeek::analyzer::tcp::ContentLine_Analyzer::DeliverStream (this=0x7f7376519a80, len=157,
    data=0x7f736daa2520 "POST / HTTP/1.1\r\nHost: hw.eyedro.com\r\nUser-Agent: 0001.0006.0000006000BF;myfreemonitor\r\nConnection: close\r\nContent-Length: 28\r\n\r\n\001", is_orig=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/ContentLine.cc:83
#14 0x000055be625e046b in zeek::analyzer::Analyzer::NextStream (this=0x7f7376519a80, len=157,
    data=0x7f736daa2520 "POST / HTTP/1.1\r\nHost: hw.eyedro.com\r\nUser-Agent: 0001.0006.0000006000BF;myfreemonitor\r\nConnection: close\r\nContent-Length: 28\r\n\r\n\001", is_orig=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/Analyzer.cc:215
#15 0x000055be625e0443 in zeek::analyzer::Analyzer::NextStream (this=0x7f7372cf8800, len=157,
    data=0x7f736daa2520 "POST / HTTP/1.1\r\nHost: hw.eyedro.com\r\nUser-Agent: 0001.0006.0000006000BF;myfreemonitor\r\nConnection: close\r\nContent-Length: 28\r\n\r\n\001", is_orig=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/Analyzer.cc:211
#16 0x000055be625e0981 in zeek::analyzer::Analyzer::ForwardStream (this=0x7f73697528c0, len=157,
    data=0x7f736daa2520 "POST / HTTP/1.1\r\nHost: hw.eyedro.com\r\nUser-Agent: 0001.0006.0000006000BF;myfreemonitor\r\nConnection: close\r\nContent-Length: 28\r\n\r\n\001", is_orig=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/Analyzer.cc:283
#17 0x000055be62bad289 in zeek::analyzer::tcp::TCP_Reassembler::Deliver (this=0x7f736131b800, seq=1, len=157,
    data=0x7f736daa2520 "POST / HTTP/1.1\r\nHost: hw.eyedro.com\r\nUser-Agent: 0001.0006.0000006000BF;myfreemonitor\r\nConnection: close\r\nContent-Length: 28\r\n\r\n\001")
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Reassembler.cc:409
#18 0x000055be62bad8c6 in zeek::analyzer::tcp::TCP_Reassembler::DeliverBlock (this=0x7f736131b800, seq=1, len=157,
    data=0x7f736daa2520 "POST / HTTP/1.1\r\nHost: hw.eyedro.com\r\nUser-Agent: 0001.0006.0000006000BF;myfreemonitor\r\nConnection: close\r\nContent-Length: 28\r\n\r\n\001")
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Reassembler.cc:546
#19 0x000055be62bace58 in zeek::analyzer::tcp::TCP_Reassembler::BlockInserted (this=0x7f736131b800,
    it={first = 1, second = {seq = 1, upper = 158, block = 0x7f736daa2520 "POST / HTTP/1.1\r\nHost: hw.eyedro.com\r\nUser-Agent: 0001.0006.0000006000BF;myfreemonitor\r\nConnection: close\r\nContent-Length: 28\r\n\r\n\001"}}) at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Reassembler.cc:360
#20 0x000055be631df7ba in zeek::Reassembler::NewBlock (this=0x7f736131b800, t=1718714984.3202691, seq=1, len=157, data=0x7f73796d43b0 "") at /usr/local/src/zeek-6.2.1/src/Reassem.cc:332
#21 0x000055be62bad3c1 in zeek::analyzer::tcp::TCP_Reassembler::DataSent (this=0x7f736131b800, t=1718714984.3202691, seq=1, len=157, data=0x7f73796d43b0 "", arg_flags=..., replaying=true)
    at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Reassembler.cc:442
#22 0x000055be62baa1df in zeek::analyzer::tcp::TCP_Endpoint::DataSent (this=0x7f73747ecce0, t=1718714984.3202691, seq=1, len=157, caplen=157, data=0x7f73796d43b0 "", ip=0x7f736161bd50,
    tp=0x7f73796d439c) at /usr/local/src/zeek-6.2.1/src/analyzer/protocol/tcp/TCP_Endpoint.cc:173
#23 0x000055be62c30767 in zeek::packet_analysis::TCP::TCPSessionAdapter::Process (this=0x7f73697528c0, is_orig=true, tp=0x7f73796d439c, len=157,
    ip=std::shared_ptr<zeek::IP_Hdr> (use count 2, weak count 0) = {...}, data=0x7f73796d43b0 "", remaining=157)
    at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/tcp/TCPSessionAdapter.cc:623
#24 0x000055be62c2e225 in zeek::packet_analysis::TCP::TCPAnalyzer::DeliverPacket (this=0x7f73869c7d50, c=0x7f735eee2fc0, t=1718714984.3202691, is_orig=true, remaining=157, pkt=0x7f7386e1c648)
    at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/tcp/TCP.cc:111
#25 0x000055be62c239ef in zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket (this=0x7f73869c7d50, len=177, data=0x7f73796d439c "", pkt=0x7f7386e1c648)
    at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/ip/IPBasedAnalyzer.cc:88
#26 0x000055be62bf1c2d in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x7f7386a49db0, len=177, data=0x7f73796d439c "", packet=0x7f7386e1c648, identifier=6)
    at /usr/local/src/zeek-6.2.1/src/packet_analysis/Analyzer.cc:117
#27 0x000055be62c20506 in zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket (this=0x7f7386a49db0, len=177, data=0x7f73796d439c "", packet=0x7f7386e1c648)
    at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/ip/IP.cc:265
#28 0x000055be62bf1c2d in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x7f738cf175d0, len=197, data=0x7f73796d4388 "", packet=0x7f7386e1c648, identifier=2048)
    at /usr/local/src/zeek-6.2.1/src/packet_analysis/Analyzer.cc:117
#29 0x000055be62c05a4e in zeek::packet_analysis::Ethernet::EthernetAnalyzer::AnalyzePacket (this=0x7f738cf175d0, len=211, data=0x7f73796d437a "", packet=0x7f7386e1c648) at /usr/local/src/zeek-6.2.1/src/packet_analysis/protocol/ethernet/Ethernet.cc:45
#30 0x000055be62bf1c2d in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x7f7386a4a530, len=211, data=0x7f73796d437a "", packet=0x7f7386e1c648, identifier=1) at /usr/local/src/zeek-6.2.1/src/packet_analysis/Analyzer.cc:117
#31 0x000055be62bf758f in zeek::packet_analysis::Manager::ProcessPacket (this=0x7f738ce7e8c0, packet=0x7f7386e1c648) at /usr/local/src/zeek-6.2.1/src/packet_analysis/Manager.cc:116
#32 0x000055be631f422b in zeek::run_state::detail::dispatch_packet (pkt=0x7f7386e1c648, pkt_src=0x7f7386e1c600) at /usr/local/src/zeek-6.2.1/src/RunState.cc:242
#33 0x000055be62de4e35 in zeek::iosource::PktSrc::Process (this=0x7f7386e1c600) at /usr/local/src/zeek-6.2.1/src/iosource/PktSrc.cc:120
#34 0x000055be631f458f in zeek::run_state::detail::run_loop () at /usr/local/src/zeek-6.2.1/src/RunState.cc:289
#35 0x000055be625ddaf5 in main (argc=17, argv=0x7ffe18b6b5a8) at /usr/local/src/zeek-6.2.1/src/main.cc:93
```

Let me know what other information I can provide.  I don't have a capture of the network traffic, but can look into getting it if the above is not sufficient.

### PR DESCRIPTION
**Pull request by awelzel**
When Zeek flips roles of a HTTP connection subsequent to the HTTP analyzer being attached, that analyzer would not update its own ContentLine analyzer state, resulting in the wrong ContentLine analyzer being switched into plain delivery mode.

In debug builds, this would result in assertion failures, in production builds, the HTTP analyzer would receive HTTP bodies as individual header lines, or conversely, individual header lines would be delivered as a large chunk from the ContentLine analyzer.

PCAPs were generated locally using tcprewrite to select well-known-http ports for both endpoints, then editcap to drop the first SYN packet.

Kudos to @JordanBarnartt for keeping at it.

Closes #3789

### CODE REVIEW

File: src/analyzer/protocol/http/HTTP.cc [hunk 1]
```diff
@@ -1020,6 +1020,32 @@ void HTTP_Analyzer::Undelivered(uint64_t seq, int len, bool is_orig) {
...
 
+void HTTP_Analyzer::FlipRoles() {
+    analyzer::tcp::TCP_ApplicationAnalyzer::FlipRoles();
+
+    // If FlipRoles() is invoked after we've upgraded to something,
+    // don't do anything. This shouldn't happen as flipping of TCP
+    // connections currently happens before any data is transferred,
+    // but better safe than sorry.
+    if ( upgraded || pia )
+        return;
```
Comment (rsmmr) [inline src/analyzer/protocol/http/HTTP.cc:1031]: If we have a PIA, could we instead pass on the `FlipRoles()`?

Comment (rsmmr) [reply src/analyzer/protocol/http/HTTP.cc:1031]: Also wondering whether this deserves a weird, too, given that we do one below if we've seen requests/replies?

File: src/analyzer/protocol/http/HTTP.cc [hunk 2]
```diff
@@ -1020,6 +1020,32 @@ void HTTP_Analyzer::Undelivered(uint64_t seq, int len, bool is_orig) {
...
+        Weird("HTTP_late_flip_roles");
+        SetSkip(true);
+        return;
+    }
+
+    // IsOrig() of the support analyzer has been updated, but we still
+    // need to change our state.
+    std::swap(content_line_orig, content_line_resp);
+    content_line_orig->SetSkipPartial(false);
+    content_line_resp->SetSkipPartial(true);
```
Comment (rsmmr) [inline src/analyzer/protocol/http/HTTP.cc:1046]: These seems to assume which way we're flipping. That's in practice probably  valid, but in principle `FlipRoles()` could flip either way, so I think this should instead flip the partial flags, too, instead of hardcoding the new ones.

**Review by rsmmr — COMMENTED** [review]
Nice. Surprising that this hasn't come up before!

File: src/analyzer/protocol/http/HTTP.cc (hunk 1 above)
Comment (awelzel) [reply src/analyzer/protocol/http/HTTP.cc:1031]: > If we have a PIA, could we instead pass on the FlipRoles()?

We add PIA as child analyzer, so that happens during `analyzer::tcp::TCP_ApplicationAnalyzer::FlipRoles()` already.

> Also wondering whether this deserves a weird, too, given that we do one below if we've seen requests/replies?

Yeah, good call.

**Comment by awelzel** [comment]
> Nice. Surprising that this hasn't come up before!

Hmm, think it needs this addition 847963e94 from mid 2022 (and possibly your follow-up 6fbebc5e9) plus source and response ports both being in likely server ports. So fairly recent and not all that likely either and not resulting in a crash unless `--enable-debug` is on.

**Review by rsmmr — APPROVED** [review]
