### PR TITLE
Fix printing of small floating point values

### LINKED ISSUE #1244: Default floating-point formatting misrepresents small numbers
Per https://try.zeek.org/#/tryzeek/saved/461913, the statement:
```
print 0.0000000000005;
```
produces the output:
```
0.0
```
rather than what I'd expect, which is:
```
5e-13
```

The same occurs for the explicit statement:
```
print 5e-13;
```

The underlying problem appears to be that while `modp_dtoa2` has logic for converting very large values to scientific notation, it doesn't have corresponding logic for very small values.

### PR DESCRIPTION
**Pull request by jsiwek**
Fixes #1244

Changes modp_dtoa2() to use scientific notation for small values

This fixes problems where printing floating point numbers less than
10^-6 output as "0.0".  Such numbers now use using scientific notation
and preserve the value's actual floating point representation.

(Also improved output of values like `1.e-13` to instead use `1e-13`)

### CODE REVIEW

File: src/modp_numtoa.c [hunk 1]
```diff
@@ -287,6 +293,14 @@ void modp_dtoa2(double value, char* str, int prec)
         prec = 9;
     }
 
+    double smallest = _pow10r[prec];
+
+    if (value != 0.0 && value < smallest) {
```
Comment (rsmmr) [inline src/modp_numtoa.c:298]:
```suggestion
    if ( value != 0.0 && value < smallest ) {
```

**Review by rsmmr — APPROVED** [review]
