### PR TITLE
Return fully-escaped string if utf8 conversion fails

### LINKED ISSUE #1581: Fully-escape unicode strings with invalid characters
@sethhall and I were discussing this problem in relation to https://github.com/zeek/zeek/pull/1437, where a UTF-8 encoding issue came up with one of the tests that was failing due to his changes. The failing case was this:

```
  -XXXXXXXXXX.XXXXXX	XXXXXXXXXXX	192.168.1.105	49613	65.55.53.190	80	1	GET	watson.microsoft.com	/StageOne/Generic/PCA2/mdd_1_3_exe/1_3_0_0/mdd/unknown/\xe8\x93\x93\xca\x86\xef\xbf\xbe\xef\xbf\xbf\xec\xb4\x91\xe7\x9e\x99\xef\xbf\xbd\xe7\x9e\x99\xeb\xb2\xb9\xd7\x9c\xee\x8b\xa0\xda\xa0/200/-1.htm?LCID=1033&OS=6.0.6002.2.00010100.2.0.6.18005	-	1.1	MSDW	-	0	1635	404	Not Found	-	-	(empty)	-	-	-	-	-	-	F8p4Qn20NOvGmbt434	-	text/html	USER-AGENT,HOST,CONNECTION	-	-	/StageOne/Generic/PCA2/mdd_1_3_exe/1_3_0_0/mdd/unknown/%E8%93%93%CA%86%EF%BF%BE%EF%BF%BF%EC%B4%91%E7%9E%99%EF%BF%BD%E7%9E%99%EB%B2%B9%D7%9C%EE%8B%A0%DA%A0/200/-1.htm?LCID,OS
  +XXXXXXXXXX.XXXXXX	XXXXXXXXXXX	192.168.1.105	49613	65.55.53.190	80	1	GET	watson.microsoft.com	/StageOne/Generic/PCA2/mdd_1_3_exe/1_3_0_0/mdd/unknown/蓓ʆ��촑瞙�瞙벹לڠ/200/-1.htm?LCID=1033&OS=6.0.6002.2.00010100.2.0.6.18005	-	1.1	MSDW	-	0	1635	404	Not Found	-	-	(empty)	-	-	-	-	-	-	F8p4Qn20NOvGmbt434	-	text/html	USER-AGENT,HOST,CONNECTION	-	-	/StageOne/Generic/PCA2/mdd_1_3_exe/1_3_0_0/mdd/unknown/%E8%93%93%CA%86%EF%BF%BE%EF%BF%BF%EC%B4%91%E7%9E%99%EF%BF%BD%E7%9E%99%EB%B2%B9%D7%9C%EE%8B%A0%DA%A0/200/-1.htm?LCID,OS
```

The original URI requested here included a string of what is probably intended to just be byte data, but we attempt to decode it into UTF-8 and display it as such. The problem is that because it's just random data, it includes what are technically-valid but not-really-valid glyphs:

```
$ printf "\xE8\x93\x93\xCA\x86\xEF\xBF\xBE\xEF\xBF\xBF\xEC\xB4\x91\xE7\x9E\x99\xEF\xBF\xBD\xE7\x9E\x99\xEB\xB2\xB9\xD7\x9C\xEE\x8B\xA0\xDA\xA0" | uniname -r
No LINES variable in environment so unable to determine lines per page.
Using default of 24.
character  byte       UTF-32   encoded as     glyph   range                                   name
        0          0  0084D3   E8 93 93       蓓      CJK Unified Ideographs                  No character name available
        1          3  000286   CA 86          ʆ      IPA Extensions                          LATIN SMALL LETTER ESH WITH CURL
        2          5  00FFFE   EF BF BE       �      Specials                                Undefined
        3          8  00FFFF   EF BF BF       �      Specials                                Undefined
        4         11  00CD11   EC B4 91       촑      Hangul Syllables                        HANGUL SYLLABLE COLG
        5         14  007799   E7 9E 99       瞙      CJK Unified Ideographs                  No character name available
        6         17  00FFFD   EF BF BD       �      Specials                                REPLACEMENT CHARACTER
        7         20  007799   E7 9E 99       瞙      CJK Unified Ideographs                  No character name available
        8         23  00BCB9   EB B2 B9       벹      Hangul Syllables                        HANGUL SYLLABLE BET
        9         26  0005DC   D7 9C          ל      Hebrew                                  HEBREW LETTER LAMED
       10         28  00E2E0   EE 8B A0             Private Use Area - Conlang Xaini        No character name available
       11         31  0006A0   DA A0          ڠ      Arabic                                  ARABIC LETTER AIN WITH THREE DOTS ABOVE
```

Our current UTF-8 conversion code passes those characters through as such because they're valid byte sequences, even though they probably shouldn't be. This part should be fixed, especially the "Private Use Area" values. Those should definitely be left as escaped characters.

The larger question is whether or not we should move to an all-or-nothing model for converting strings of bytes to UTF-8. Right now we convert whatever we can but escape anything that's valid sequence. Does it make more sense to try to do the conversion, but if any one sequence fails it means the entire string should be escaped?

### PR DESCRIPTION
**Pull request by timwoj**
This adds a new function for validating UTF-8 sequences by converting to
UTF-32. This allows us to also check for various blocks of codepoints
that we consider invalid while checking for valid sequences in general.

Fixes #1581

### CODE REVIEW

File: src/util.cc [hunk 1]
```diff
@@ -2406,6 +2406,33 @@ TEST_CASE("util json_escape_utf8")
...
+	std::array<UTF32, 2> output;
+	UTF32* output2 = output.data();
+	auto result = ConvertUTF8toUTF32(&start, end, &output2, output2+1, strictConversion);
+	if ( result != conversionOK )
+		return false;
+
+	if ( output[0] >= 0x0000 && output[0] <= 0x001F )
+		// Control characters
+		return false;
+	if ( output[0] >= 0xE000 && output[0] <= 0xF8FF )
```
Comment (timwoj) [inline src/util.cc:2428]: Whoops, missed an `else` here.

File: src/util.cc [hunk 2]
```diff
@@ -2428,38 +2462,56 @@ string json_escape_utf8(const string& val)
...
+				utf_result.append(val, idx, char_size);
+				idx += char_size;
+				}
+			}
 		}
 
 	// Insert any of the remaining bytes into the string as escaped bytes
 	for ( ; idx < val_size; ++idx )
-		result.append(json_escape_byte(val[idx]));
+		escaped_result.append(json_escape_byte(val[idx]));
```
Comment (rsmmr) [inline src/util.cc:2509]: Can this loop still happen? The condition is the same as with the previous loop, and that one has no `break`.

File: src/util.cc [hunk 3]
```diff
@@ -2414,10 +2441,17 @@ string json_escape_utf8(const string& val)
...
+	// escaped version otherwise. This uses slightly more memory but it avoids looping through all
+	// of the characters a second time in the case of a bad utf8 sequence.
+	string utf_result;
+	utf_result.reserve(val_size);
+	string escaped_result;
+	escaped_result.reserve(val_size);
+
+	bool found_bad = false;
 	size_t idx;
 	for ( idx = 0; idx < val_size; )
```
Comment (rsmmr) [inline src/util.cc:2456]: Suggest to not use a for-loop here, it's easy to miss that there's no auto-increment:
```suggestion
	size_t idx = 0;
	while ( idx < val_size )
```

File: src/util.cc [hunk 4]
```diff
@@ -2428,38 +2462,56 @@ string json_escape_utf8(const string& val)
...
-			continue;
-			}
+			// Find out how long the next character should be.
+			unsigned int char_size = getNumBytesForUTF8(ch);
 
-		result.append(val, idx, char_size);
-		idx += char_size;
+			// If it says that it's a single character or it's not an valid string UTF8 sequence, insert
+			// the one escaped byte into the string, step forward one, and go to the next character.
+			if ( char_size == 0 || idx+char_size > val_size ||
```
Comment (rsmmr) [inline src/util.cc:2491]: Is `getNumBytesForUTF8(ch)` returning zero if it's a single character?

File: src/util.cc [hunk 5]
```diff
@@ -2428,38 +2462,56 @@ string json_escape_utf8(const string& val)
...
+			     ! check_ok_utf8(val_data+idx, val_data+idx+char_size) )
+				{
+				found_bad = true;
+				escaped_result.append(json_escape_byte(ch));
+				++idx;
+				continue;
+				}
+			else
+				{
+				utf_result.append(val, idx, char_size);
```
Comment (rsmmr) [inline src/util.cc:2501]: Does this need to append to `escaped_result` too?

File: src/util.cc (hunk 4 above)
Comment (timwoj) [reply src/util.cc:2491]: Yes. It's possible for it to return 0. See https://github.com/zeek/zeek/blob/master/src/ConvertUTF.c#L117-L133.

File: src/util.cc (hunk 2 above)
Comment (timwoj) [reply src/util.cc:2509]: Oh weird. There wasn't a break there before either. That must have been a leftover artifact from a previous change.

File: src/util.cc (hunk 4 above)
Comment (rsmmr) [reply src/util.cc:2494]: Oh, but look at this:

 ```
unsigned getNumBytesForUTF8(UTF8 first) {
  return trailingBytesForUTF8[first] + 1;
}
```

 That will always return >= 1.

Comment (timwoj) [reply src/util.cc]: Ah, you are correct. Now I'm confused though, because according to that table I linked, characters 128-192 are considered a single byte. That means we wouldn't ever insert those characters (things like the copyright symbol, etc). It's probably ok to just take that check out entirely, since it hasn't been doing anything anyways.

That said, there's a bunch of non-printable characters in that second block of 127 characters that we should skip (see https://codepoints.net/latin-1_supplement).

Comment (timwoj) [reply src/util.cc]: Ah, https://codepoints.net/U+00C7 shows that the UTF-8 version of at least one of those characters is actually a two-byte sequence (and that's true for all of them). I wonder why that function returns `1` for a bunch of them.

**Comment by timwoj** [comment]
@rsmmr Anything else on this?

File: src/util.cc [hunk 6]
```diff
@@ -2414,52 +2446,75 @@ string json_escape_utf8(const string& val)
...
-			continue;
-			}
+			// Find out how long the next character should be.
+			unsigned int char_size = getNumBytesForUTF8(ch);
 
-		result.append(val, idx, char_size);
-		idx += char_size;
+			// If we don't have enough data for this character or it's an invalid sequence,
+			// insert the one escaped byte into the string and go to the next character.
+			if ( idx+char_size > val_size ||
```
Comment (rsmmr) [inline src/util.cc:2496]: Just double-checking because I can't make up my mind: this shouldn't be `idx+char_size >= val_size`, correct?

File: src/util.cc [hunk 7]
```diff
@@ -2414,52 +2446,75 @@ string json_escape_utf8(const string& val)
...
+			     ! check_ok_utf8(val_data+idx, val_data+idx+char_size) )
```
Comment (rsmmr) [inline src/util.cc:2497]:
```suggestion
			     ! check_ok_utf8(val_data + idx, val_data + idx + char_size) )
```

**Review by rsmmr — APPROVED** [review]
Just a couple question, otherwise LGTM.

File: src/util.cc (hunk 6 above)
Comment (timwoj) [reply src/util.cc:2496]: If val_size is 2 (the string is one two-byte UTF8 sequence long), the index is zero, and the char_size is 2 (for the two bytes in the sequence), we'd want it to be processed as UTF8. If we set that `>=`, it would get escaped incorrectly.

File: src/ConvertUTF.c [hunk 8]
```diff
@@ -626,7 +626,6 @@ ConversionResult ConvertUTF8toUTF16 (
         }
     }
     *sourceStart = source;
-    *targetStart = target;
```
[the remark this answers is not in the document]
Comment (timwoj) [reply src/ConvertUTF.c:629]: Ah, that change isn't necessary anymore. I'm calling the UTF32 version now instead. I'll drop the commit.

File: src/util.cc (hunk 7 above)
Comment (timwoj) [reply src/util.cc:2497]: Fixed.

**Comment by timwoj** [comment]
Fixed the one formatting issue, dropped the commit that changes ConvertUTF, and squashed everything back down into one commit.

**Review by rsmmr — APPROVED** [review]
