### PR TITLE
fix cases where ssh_encrypted_packet event wasn't raised

### LINKED ISSUE #566: SSH Analyzer Skipping Some Encrypted Messages
The first encrypted message of an SSH session is not processed if it is included in a packet which also includes an SSH DH message or NewKeys message. This means the `ssh_encrypted_packet()` event is not raised under certain conditions such as specific client + server combinations. See the attached pcaps
[pcaps.zip](https://github.com/zeek/zeek/files/3570644/pcaps.zip)

In the pcap named ssh_server_sends_first_enc_pkt_with_newkeys.pcap the server sends its DH reply, NewKeys, and an encrypted message (the first of the session) all in the same packet (packet 12). The encrypted message is not processed by Zeek's SSH analyzer as is expected. The first encrypted packet processed by Zeek's SSH protocol analyzer is packet 15.

In the pcap named ssh_client_sends_first_enc_pkt_with_newkeys.pcap, the client includes an  encrypted message (the first of the session) in the packet carrying its NewKeys message (packet 13). Yet, the first encrypted message processed by Zeek's protocol analyzer is packet 15.

This bug can be demonstrated via the following script:
```
global pkts: count = 0;
redef SSH::disable_analyzer_after_detection = F;

event ssh_encrypted_packet (c: connection, orig: bool, len: count) {
  if (pkts < 2) {
    print orig ? len : len * -1;
    pkts = pkts + 1;
  } else {
    return;
  }
}
```

Output of the script when run on the attached pcaps.
```
$ bro test.bro -Cr ssh_client_sends_first_enc_pkt_with_newkeys.pcap 
-64
80

$ bro test.bro -Cr ssh_server_sends_first_enc_pkt_with_newkeys.pcap
44
-44
```

In both cases, the first encrypted packet to raise the `ssh_encrypted_packet()` event is the first encrypted packet NOT included with any type of SSH message.

### PR DESCRIPTION
**Pull request by jsiwek**
Fixes #566

### CODE REVIEW

File: src/analyzer/protocol/ssh/SSH.cc [hunk 1]
```diff
@@ -83,11 +88,31 @@ void SSH_Analyzer::Undelivered(uint64_t seq, int len, bool orig)
...
+		return;
+
+	if ( orig )
+		saw_encrypted_client_data = true;
+	else
 		{
+		// If the client hasn't sent any encrypted data yet, but the
+		// server is, just ignore it until seeing encrypted client data.
+		if ( ! saw_encrypted_client_data )
+			return;
```
Comment (grigorescu) [inline src/analyzer/protocol/ssh/SSH.cc]: Should this generate a weird?

**Comment by rsmmr** [comment]
Looks like this is ready, I'll merge.
