### PR TITLE
Fix UB during early shutdown on OpenSSL state

### LINKED ISSUE #2084: Zeek test consistently crashing due to broker->caf->openssl segfault
This happens to me on master every time when running the plugins.plugin-withpatchversion test:

The backtrace points at an issue when CAF is calling `make_ctx` in a tread:

```bash
$ lldb -- zeek -b -N Testing::WithPatchVersion
(lldb) target create "zeek"
r
Current executable set to 'zeek' (x86_64).
(lldb) settings set -- target.run-args  "-b" "-N" "Testing::WithPatchVersion"
(lldb) r
Process 18613 launched: '/Users/johanna/zeek/main/build/src/zeek' (x86_64)
Testing::WithPatchVersion - Testing a plugin with a specified patch version (dynamic, version 0.1.4)
Process 18613 stopped
* thread #8, stop reason = EXC_BAD_ACCESS (code=1, address=0x5225c536)
    frame #0: 0x00000001055b3ee8 libcrypto.3.dylib`OPENSSL_LH_retrieve + 9
libcrypto.3.dylib`OPENSSL_LH_retrieve:
->  0x1055b3ee8 <+9>:  movl   $0x0, 0xa8(%rdi)
    0x1055b3ef2 <+19>: leaq   -0x10(%rbp), %rdx
    0x1055b3ef6 <+23>: callq  0x1055b3d13               ; getrn
    0x1055b3efb <+28>: xorl   %ecx, %ecx
Target 0: (zeek) stopped.
(lldb) bt
* thread #8, stop reason = EXC_BAD_ACCESS (code=1, address=0x5225c536)
  * frame #0: 0x00000001055b3ee8 libcrypto.3.dylib`OPENSSL_LH_retrieve + 9
    frame #1: 0x00000001055e420b libcrypto.3.dylib`ossl_method_store_cache_get + 103
    frame #2: 0x0000000105596e2e libcrypto.3.dylib`inner_evp_generic_fetch + 363
    frame #3: 0x0000000105596ca2 libcrypto.3.dylib`evp_generic_fetch + 65
    frame #4: 0x00000001055967b7 libcrypto.3.dylib`EVP_CIPHER_fetch + 49
    frame #5: 0x00000001050b685c libssl.3.dylib`ssl_evp_cipher_fetch + 56
    frame #6: 0x00000001050aaf10 libssl.3.dylib`ssl_load_ciphers + 56
    frame #7: 0x00000001050b344f libssl.3.dylib`SSL_CTX_new_ex + 356
    frame #8: 0x000000010a86b904 libbroker.4.dylib`caf::net::openssl::make_ctx(method=0x00000001050fb150) at openssl_transport.hpp:62:18
    frame #9: 0x000000010a864bad libbroker.4.dylib`broker::internal::(anonymous namespace)::ssl_context_from_cfg(cfg=std::__1::shared_ptr<broker::openssl_options>::element_type @ 0x00006000033835d8 strong=1 weak=1) at connector.cc:151:14
    frame #10: 0x000000010a863120 libbroker.4.dylib`broker::internal::connector::run_impl(this=0x0000600003d0d968, sub=0x000060000007c630, filter=0x0000600002d05918) at connector.cc:1940:23
    frame #11: 0x000000010a862bbf libbroker.4.dylib`broker::internal::connector::run(this=0x0000600003d0d968) at connector.cc:1869:5
    frame #12: 0x000000010a74a5ae libbroker.4.dylib`broker::(anonymous namespace)::connector_task::start(this=0x0000600000352e88)::'lambda'()::operator()() const at endpoint.cc:388:12
    frame #13: 0x000000010a74a545 libbroker.4.dylib`decltype(__f=0x0000600000352e88)::connector_task::start(caf::actor_system&, broker::endpoint_id, std::__1::shared_ptr<broker::openssl_options>)::'lambda'()>(fp)()) std::__1::__invoke<broker::(anonymous namespace)::connector_task::start(caf::actor_system&, broker::endpoint_id, std::__1::shared_ptr<broker::openssl_options>)::'lambda'()>(broker::(anonymous namespace)::connector_task::start(caf::actor_system&, broker::endpoint_id, std::__1::shared_ptr<broker::openssl_options>)::'lambda'()&&) at type_traits:3918:1
    frame #14: 0x000000010a74a4e5 libbroker.4.dylib`void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, broker::(anonymous namespace)::connector_task::start(caf::actor_system&, broker::endpoint_id, std::__1::shared_ptr<broker::openssl_options>)::'lambda'()>(__t=size=2, (null)=__tuple_indices<> @ 0x000070000c085f68)::connector_task::start(caf::actor_system&, broker::endpoint_id, std::__1::shared_ptr<broker::openssl_options>)::'lambda'()>&, std::__1::__tuple_indices<>) at thread:287:5
    frame #15: 0x000000010a749cb2 libbroker.4.dylib`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, broker::(anonymous namespace)::connector_task::start(caf::actor_system&, broker::endpoint_id, std::__1::shared_ptr<broker::openssl_options>)::'lambda'()> >(__vp=0x0000600000352e80) at thread:298:5
    frame #16: 0x00007ff8168d04e1 libsystem_pthread.dylib`_pthread_start + 125
    frame #17: 0x00007ff8168cbf6b libsystem_pthread.dylib`thread_start + 15
```

@Neverlord - this might be one for you - I think this is similar to the issue that you recently fixed in the ALM branch.

This is on OS-X 12.3.1 (21E258). Configure is called like this: 

```
CFLAGS="-ftrapv" CXXFLAGS="-ftrapv" ./configure --prefix=/Users/johanna/zeek/install --enable-debug --disable-broker-tests --generator=Ninja --disable-zkg --disable-zeekctl --disable-python --ccache
```

Configure output:

```
$ CFLAGS="-ftrapv" CXXFLAGS="-ftrapv" ./configure --prefix=/Users/johanna/zeek/install --enable-debug --disable-broker-tests --generator=Ninja --disable-zkg --disable-zeekctl --disable-python --ccache
Build Directory : build
Source Directory: /Users/johanna/zeek/main
Using cmake version 3.22.4

-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test test_arch_x64
-- Performing Test test_arch_x64 - Success
-- Performing Test test_arch_aarch64
-- Performing Test test_arch_aarch64 - Failed
-- Performing Test test_arch_arm
-- Performing Test test_arch_arm - Failed
-- Performing Test test_arch_power
-- Performing Test test_arch_power - Failed
-- Determined target architecture (for hashing): x86_64
-- Using ccache: /opt/local/bin/ccache
-- Found sed: /usr/bin/sed
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.9")
-- Found FLEX: /opt/local/bin/flex (found version "2.6.4")
-- Found BISON: /opt/local/bin/bison
-- Found PCAP: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libpcap.tbd
-- Performing Test PCAP_LINKS_SOLO
-- Performing Test PCAP_LINKS_SOLO - Success
-- Looking for pcap_get_pfring_id
-- Looking for pcap_get_pfring_id - not found
-- Looking for pcap_dump_open_append
-- Looking for pcap_dump_open_append - found
-- Found OpenSSL: /opt/local/lib/libcrypto.dylib (found version "3.0.2")
-- Performing Test ns_initparse_works_none
-- Performing Test ns_initparse_works_none - Failed
-- Performing Test res_mkquery_works_none
-- Performing Test res_mkquery_works_none - Failed
-- Performing Test ns_initparse_works_resolv
-- Performing Test ns_initparse_works_resolv - Success
-- Performing Test res_mkquery_works_resolv
-- Performing Test res_mkquery_works_resolv - Success
-- Found BIND: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libresolv.tbd
-- Found ZLIB: /opt/local/lib/libz.dylib (found version "1.2.12")
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned int
-- Check size of unsigned int - done

==================|  BinPAC Build Summary  |====================
Version:           0.58.0
SO version:        0

Build Type:        Debug
Debug mode:        true
Install prefix:    /Users/johanna/zeek/install
Shared libs:       yes
Static libs:       no

CC:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CFLAGS:            -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -g
CXX:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXXFLAGS:          -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -g
CPP:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

================================================================

-- Found BinPAC: binpac
-- Performing Test cxx17_already_works
-- Performing Test cxx17_already_works - Failed
-- Performing Test cxx17_works
-- Performing Test cxx17_works - Success

====================|  Bifcl Build Summary  |=====================

Build type:        Debug
Build dir:         /Users/johanna/zeek/main/build/auxil/bifcl
Install prefix:    /Users/johanna/zeek/install
Debug mode:        true

CC:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CFLAGS:            -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -g
CXX:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXXFLAGS:          -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -std=c++17 -g
CPP:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

================================================================


===================|  Gen-ZAM Build Summary  |==================


Build type:        Debug
Build dir:         /Users/johanna/zeek/main/build/auxil/gen-zam
Install prefix:    /Users/johanna/zeek/install
Debug mode:        true

CC:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CFLAGS:            -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -g
CXX:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXXFLAGS:          -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -std=c++17 -g
CPP:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

================================================================


=================|  Paraglob Config Summary  |===================
BUILD_TYPE:          DEBUG
CXX_FLAGS:           -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -std=c++17 -Wall -g
=================================================================

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test BROKER_HAS_STD_FILESYSTEM
-- Performing Test BROKER_HAS_STD_FILESYSTEM - Success
-- Looking for include file emmintrin.h
-- Looking for include file emmintrin.h - found
-- Performing Test atomic64_builtin
-- Performing Test atomic64_builtin - Success
-- Using bundled CAF
-- Performing Test has_64bit_atomic
-- Performing Test has_64bit_atomic - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Using bundled CAF incubator

==================|  Broker Config Summary  |====================
Version:         2.2.0-263
SO version:      4

Build Type:      Debug
Install prefix:  /Users/johanna/zeek/install
Library prefix:  lib
Shared libs:     yes
Static libs:     no

CC:              /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CFLAGS:          -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -g
CXX:             /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXXFLAGS:        -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -std=c++17 -g

CAF:             0.18.5
Python bindings: no
Zeek:            /Users/johanna/zeek/main/build/zeek-path-dev.sh
=================================================================

-- Could NOT find LibMMDB (missing: LibMMDB_LIBRARY LibMMDB_INCLUDE_DIR)
-- Could NOT find FTS (missing: FTS_LIBRARY)
-- Looking for htonll
-- Looking for htonll - found
-- Check size of long int
-- Check size of long int - done
-- Check size of long long
-- Check size of long long - done
-- Check size of void *
-- Check size of void * - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of u_int32_t
-- Check size of u_int32_t - done
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of u_int8_t
-- Check size of u_int8_t - done
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Check size of struct ip6_opt
-- Check size of struct ip6_opt - done
-- Check size of struct ip6_ext
-- Check size of struct ip6_ext - done
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file netinet/ether.h
-- Looking for include file netinet/ether.h - not found
-- Looking for 4 include files sys/socket.h, ..., netinet/if_ether.h
-- Looking for 4 include files sys/socket.h, ..., netinet/if_ether.h - found
-- Looking for 4 include files sys/socket.h, ..., netinet/ip6.h
-- Looking for 4 include files sys/socket.h, ..., netinet/ip6.h - found
-- Looking for 3 include files sys/socket.h, ..., net/ethernet.h
-- Looking for 3 include files sys/socket.h, ..., net/ethernet.h - found
-- Looking for include file sys/ethernet.h
-- Looking for include file sys/ethernet.h - not found
-- Looking for include file net/ethertypes.h
-- Looking for include file net/ethertypes.h - not found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include files time.h, sys/time.h
-- Looking for include files time.h, sys/time.h - found
-- Looking for include file os-proto.h
-- Looking for include file os-proto.h - not found
-- Performing Test HAVE_READLINE_HISTORY_ENTRIES
-- Performing Test HAVE_READLINE_HISTORY_ENTRIES - Failed
-- Looking for include files stdio.h, readline/readline.h
-- Looking for include files stdio.h, readline/readline.h - found
-- Looking for include files stdio.h, readline/history.h
-- Looking for include files stdio.h, readline/history.h - found
-- Performing Test SIN_LEN
-- Performing Test SIN_LEN - Success
-- Looking for IPPROTO_HOPOPTS
-- Looking for IPPROTO_HOPOPTS - found
-- Looking for IPPROTO_IPV6
-- Looking for IPPROTO_IPV6 - found
-- Looking for IPPROTO_IPV4
-- Looking for IPPROTO_IPV4 - found
-- Looking for IPPROTO_ROUTING
-- Looking for IPPROTO_ROUTING - found
-- Looking for IPPROTO_FRAGMENT
-- Looking for IPPROTO_FRAGMENT - found
-- Looking for IPPROTO_ESP
-- Looking for IPPROTO_ESP - found
-- Looking for IPPROTO_AH
-- Looking for IPPROTO_AH - found
-- Looking for IPPROTO_ICMPV6
-- Looking for IPPROTO_ICMPV6 - found
-- Looking for IPPROTO_NONE
-- Looking for IPPROTO_NONE - found
-- Looking for IPPROTO_DSTOPTS
-- Looking for IPPROTO_DSTOPTS - found
-- Looking for getopt_long
-- Looking for getopt_long - found
-- Looking for mallinfo
-- Looking for mallinfo - not found
-- Looking for mallinfo2
-- Looking for mallinfo2 - not found
-- Looking for strcasestr
-- Looking for strcasestr - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for sigset
-- Looking for sigset - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Performing Test DO_SOCK_DECL
-- Performing Test DO_SOCK_DECL - Failed
-- Performing Test SYSLOG_INT
-- Performing Test SYSLOG_INT - Failed
-- Looking for include file pcap-int.h
-- Looking for include file pcap-int.h - not found
-- Looking for pcap_freecode
-- Looking for pcap_freecode - found
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_HAS_ERROR_PARAMETER
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_HAS_ERROR_PARAMETER - Failed
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_NO_ERROR_PARAMETER
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_NO_ERROR_PARAMETER - Success
-- Looking for DLT_PPP_SERIAL
-- Looking for DLT_PPP_SERIAL - found
-- Looking for DLT_NFLOG
-- Looking for DLT_NFLOG - found
-- Performing Test including_ssl_h_works
-- Performing Test including_ssl_h_works - Success
-- Looking for include file openssl/kdf.h
-- Looking for include file openssl/kdf.h - found
-- Performing Test OPENSSL_D2I_X509_USES_CONST_CHAR
-- Performing Test OPENSSL_D2I_X509_USES_CONST_CHAR - Success
-- Performing Test OPENSSL_CORRECT_VERSION_NUMBER
-- Performing Test OPENSSL_CORRECT_VERSION_NUMBER - Success
-- Performing Test have_nameser_header
-- Performing Test have_nameser_header - Failed
-- Performing Test NEED_NAMESER_COMPAT_H
-- Performing Test NEED_NAMESER_COMPAT_H - Success
-- Looking for kqueue
-- Looking for kqueue - found
-- Looking for ares_init
-- Looking for ares_init - not found
-- Looking for res_servicename
-- Looking for res_servicename - not found
-- Looking for res_servicename in resolv
-- Looking for res_servicename in resolv - found
-- Performing Test IOS
-- Performing Test IOS - Failed
-- Performing Test IOS_V10
-- Performing Test IOS_V10 - Failed
-- Performing Test MACOS_V1012
-- Performing Test MACOS_V1012 - Success
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for socket
-- Looking for socket - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - found
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Looking for include file arpa/nameser_compat.h
-- Looking for include file arpa/nameser_compat.h - found
-- Looking for include file arpa/nameser.h
-- Looking for include file arpa/nameser.h - found
-- Looking for include file assert.h
-- Looking for include file assert.h - found
-- Looking for include file errno.h
-- Looking for include file errno.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file limits.h
-- Looking for include file limits.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - not found
-- Looking for include file netdb.h
-- Looking for include file netdb.h - found
-- Looking for include file netinet/in.h
-- Looking for include file netinet/in.h - found
-- Looking for include file net/if.h
-- Looking for include file net/if.h - found
-- Looking for include file signal.h
-- Looking for include file signal.h - found
-- Looking for include file socket.h
-- Looking for include file socket.h - not found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file stropts.h
-- Looking for include file stropts.h - not found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file sys/param.h
-- Looking for include file sys/param.h - found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/uio.h
-- Looking for include file sys/uio.h - found
-- Looking for include file time.h
-- Looking for include file time.h - found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include files sys/types.h, netinet/tcp.h
-- Looking for include files sys/types.h, netinet/tcp.h - found
-- Performing Test HAVE_SOCKLEN_T
-- Performing Test HAVE_SOCKLEN_T - Success
-- Performing Test HAVE_TYPE_SOCKET
-- Performing Test HAVE_TYPE_SOCKET - Failed
-- Performing Test HAVE_BOOL_T
-- Performing Test HAVE_BOOL_T - Success
-- Performing Test HAVE_SSIZE_T
-- Performing Test HAVE_SSIZE_T - Success
-- Performing Test HAVE_LONGLONG
-- Performing Test HAVE_LONGLONG - Success
-- Performing Test HAVE_SIG_ATOMIC_T
-- Performing Test HAVE_SIG_ATOMIC_T - Success
-- Performing Test HAVE_STRUCT_ADDRINFO
-- Performing Test HAVE_STRUCT_ADDRINFO - Success
-- Performing Test HAVE_STRUCT_IN6_ADDR
-- Performing Test HAVE_STRUCT_IN6_ADDR - Success
-- Performing Test HAVE_STRUCT_SOCKADDR_IN6
-- Performing Test HAVE_STRUCT_SOCKADDR_IN6 - Success
-- Performing Test HAVE_STRUCT_SOCKADDR_STORAGE
-- Performing Test HAVE_STRUCT_SOCKADDR_STORAGE - Success
-- Performing Test HAVE_STRUCT_TIMEVAL
-- Performing Test HAVE_STRUCT_TIMEVAL - Success
-- Looking for AF_INET6
-- Looking for AF_INET6 - found
-- Looking for O_NONBLOCK
-- Looking for O_NONBLOCK - found
-- Looking for FIONBIO
-- Looking for FIONBIO - found
-- Looking for SIOCGIFADDR
-- Looking for SIOCGIFADDR - found
-- Looking for MSG_NOSIGNAL
-- Looking for MSG_NOSIGNAL - found
-- Looking for PF_INET6
-- Looking for PF_INET6 - found
-- Looking for SO_NONBLOCK
-- Looking for SO_NONBLOCK - not found
-- Looking for CLOCK_MONOTONIC
-- Looking for CLOCK_MONOTONIC - found
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID
-- Performing Test HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID - Success
-- Performing Test HAVE_LL
-- Performing Test HAVE_LL - Success
-- Looking for bitncmp
-- Looking for bitncmp - not found
-- Looking for closesocket
-- Looking for closesocket - not found
-- Looking for CloseSocket
-- Looking for CloseSocket - not found
-- Looking for connect
-- Looking for connect - found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for freeaddrinfo
-- Looking for freeaddrinfo - found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for getenv
-- Looking for getenv - found
-- Looking for gethostbyaddr
-- Looking for gethostbyaddr - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for gethostname
-- Looking for gethostname - found
-- Looking for getnameinfo
-- Looking for getnameinfo - found
-- Looking for getservbyport_r
-- Looking for getservbyport_r - not found
-- Looking for getservbyname_r
-- Looking for getservbyname_r - not found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for if_indextoname
-- Looking for if_indextoname - found
-- Looking for inet_net_pton
-- Looking for inet_net_pton - found
-- Looking for inet_ntop
-- Looking for inet_ntop - found
-- Looking for inet_pton
-- Looking for inet_pton - found
-- Looking for ioctl
-- Looking for ioctl - found
-- Looking for ioctlsocket
-- Looking for ioctlsocket - not found
-- Looking for IoctlSocket
-- Looking for IoctlSocket - not found
-- Looking for recv
-- Looking for recv - found
-- Looking for recvfrom
-- Looking for recvfrom - found
-- Looking for send
-- Looking for send - found
-- Looking for setsockopt
-- Looking for setsockopt - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strcmpi
-- Looking for strcmpi - not found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for strncmpi
-- Looking for strncmpi - not found
-- Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for writev
-- Looking for writev - found
-- Looking for __system_property_get
-- Looking for __system_property_get - not found
-- -- Found 0 test cases for CTest

====================|  BTest Build Summary  |===================

Install prefix:      /Users/johanna/zeek/install
Python module path:  /Users/johanna/zeek/install/lib/zeek/python

================================================================


==================|  Zeek-Aux Build Summary  |==================

Install prefix:    /Users/johanna/zeek/install
Debug mode:        true

CC:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CFLAGS:            -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -g
CXX:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXXFLAGS:          -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -std=c++17 -g
CPP:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

================================================================


====================|  ZeekArchiver Build Summary  |====================

Build type:        Debug
Build dir:         /Users/johanna/zeek/main/build
Install prefix:    /Users/johanna/zeek/install

CXX:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXXFLAGS (base):   -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -std=c++17 -g
CXXFLAGS (extra):  -std=c++17;-Wall;-Wno-unused;-Werror=vla
================================================================


====================|  Zeek Build Summary  |====================

Build type:        Debug
Build dir:         /Users/johanna/zeek/main/build
Install prefix:    /Users/johanna/zeek/install
Plugin dir:        /Users/johanna/zeek/install/lib/zeek/plugins
Python module dir: /Users/johanna/zeek/install/lib/zeek/python
Zeek Script Path:  /Users/johanna/zeek/install/share/zeek
Debug mode:        true
Unit tests:        true
Builtin Plugins:

CC:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
CFLAGS:            -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -g
CXX:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXXFLAGS:          -ftrapv -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -std=c++17 -g
CPP:               /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

ZeekControl:       false
Aux. Tools:        true
BifCL:             included
BinPAC:            included
BTest:             true
BTest tooling:     all
Gen-ZAM:           included
zkg:               false

libmaxminddb:      false
Kerberos:          false
gperftools found:  false
        tcmalloc:  false
       debugging:  false
jemalloc:          false

Fuzz Targets:
Fuzz Engine:

================================================================

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/johanna/zeek/main/build
```

### PR DESCRIPTION
**Pull request by Neverlord**
Fixes #2084 (hopefully).

@timwoj am I supposed to call some member function on the `iosource_mgr` before deleting it? Seems to work that way, but I'd like to double-check with you. :)

### CODE REVIEW

**Comment by Neverlord** [comment]
Also, why are lambdas [formatted differently](https://github.com/zeek/zeek/pull/2098/commits/327f5e76f99d968676a994fcb00b7fc0375adf64)? 😛

(Probably some `clang-format` behavior we can't do much about?)

**Comment by timwoj** [comment]
> am I supposed to call some member function on the iosource_mgr before deleting it?

Nope, the destructor should take care of shutting down all of the sources and cleaning up everything.

File: src/zeek-setup.cc [hunk 1]
```diff
@@ -843,7 +856,7 @@ SetupResult setup(int argc, char** argv, Options* zopts)
 
 		if ( reporter->Errors() > 0 )
 			{
-			delete dns_mgr;
+			early_shutdown();
```
Comment (timwoj) [inline src/zeek-setup.cc:859]: Should `early_shutdown` also delete `dns_mgr`, since it looks like that deletion was lost in a few places?

Comment (Neverlord) [reply src/zeek-setup.cc:859]: I've removed the manual deletes because ASAN otherwise complains (i.e., crashes the application). There's also this comment in line 426 about cleanup dependencies:

```
// broker_mgr, timer_mgr, supervisor, and dns_mgr are deleted via iosource_mgr
```

🙂

**Review by timwoj — APPROVED** [review]
